data colected from: https://datahub.io/sports-data/english-premier-league

data exp: https://www.football-data.co.uk/notes.txt

Div = League Division

Date = Match Date (dd/mm/yy)

HomeTeam = Home Team

AwayTeam = Away Team

FTHG = Full Time Home Team Goals

FTAG = Full Time Away Team Goals

FTR = Full Time Result (H=Home Win, D=Draw, A=Away Win)

HTHG = Half Time Home Team Goals

HTAG = Half Time Away Team Goals

HTR = Half Time Result (H=Home Win, D=Draw, A=Away Win)

Referee = Match Referee

HS = Home Team Shots

AS = Away Team Shots

HST = Home Team Shots on Target

AST = Away Team Shots on Target

HC = Home Team Corners

AC = Away Team Corners

HF = Home Team Fouls Committed

AF = Away Team Fouls Committed

HY = Home Team Yellow Cards

AY = Away Team Yellow Cards

HR = Home Team Red Cards

AR = Away Team Red Cards

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
#(2003-2004)-(2021-2022) data

#_0304 = pd.read_csv('data\\0304.csv',error_bad_lines=False)
#_0405 = pd.read_csv('data\\0405.csv',error_bad_lines=False) data not good for both years
_0506 = pd.read_csv('data\\0506.csv')
_0607 = pd.read_csv('data\\0607.csv')
_0708 = pd.read_csv('data\\0708.csv')
_0809 = pd.read_csv('data\\0809.csv')
_0910 = pd.read_csv('data\\0910.csv')
_1011 = pd.read_csv('data\\1011.csv')
_1112 = pd.read_csv('data\\1112.csv')
_1213 = pd.read_csv('data\\1213.csv')
_1314 = pd.read_csv('data\\1314.csv')
_1415 = pd.read_csv('data\\1415.csv')
_1516 = pd.read_csv('data\\1516.csv')
_1617 = pd.read_csv('data\\1617.csv')
_1718 = pd.read_csv('data\\1718.csv')
_1819 = pd.read_csv('data\\1819.csv')
_1920 = pd.read_csv('data\\1920.csv')
_2021 = pd.read_csv('data\\2021.csv')
_2122 = pd.read_csv('data\\2122.csv')

In [3]:
#(2005-2006)-(2021-2022) data

_0506['Div'] = ['E0506' for _ in range(_0506.shape[0])]
_0607['Div'] = ['E0607' for _ in range(_0607.shape[0])]
_0708['Div'] = ['E0708' for _ in range(_0708.shape[0])]
_0809['Div'] = ['E0809' for _ in range(_0809.shape[0])]
_0910['Div'] = ['E0910' for _ in range(_0910.shape[0])]
_1011['Div'] = ['E1011' for _ in range(_1011.shape[0])]
_1112['Div'] = ['E1112' for _ in range(_1112.shape[0])]
_1213['Div'] = ['E1213' for _ in range(_1213.shape[0])]
_1314['Div'] = ['E1314' for _ in range(_1314.shape[0])]
_1415['Div'] = ['E1415' for _ in range(_1415.shape[0])]
_1516['Div'] = ['E1516' for _ in range(_1516.shape[0])]
_1617['Div'] = ['E1617' for _ in range(_1617.shape[0])]
_1718['Div'] = ['E1718' for _ in range(_1718.shape[0])]
_1819['Div'] = ['E1819' for _ in range(_1819.shape[0])]
_1920['Div'] = ['E1920' for _ in range(_1920.shape[0])]
_2021['Div'] = ['E2021' for _ in range(_2021.shape[0])]
_2122['Div'] = ['E2122' for _ in range(_2122.shape[0])]

df = pd.concat([_0506, _0607, _0708, _0809, _0910, _1011, _1112, _1213, _1314, _1415, _1516, _1617, _1718, _1819, _1920, _2021, _2122],
               ignore_index=True)
df.head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0506,13/08/05,Aston Villa,Bolton,2.0,2.0,D,2.0,2.0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0506,13/08/05,Everton,Man United,0.0,2.0,A,0.0,1.0,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0506,13/08/05,Fulham,Birmingham,0.0,0.0,D,0.0,0.0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0506,13/08/05,Man City,West Brom,0.0,0.0,D,0.0,0.0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0506,13/08/05,Middlesbrough,Liverpool,0.0,0.0,D,0.0,0.0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
lst, drop_cl = ['Div', 'Date','HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'Referee', 'HS',
                'AS', 'HST', 'AST', 'HF', 'AF', 'HC','AC', 'HY', 'AY', 'HR', 'AR'], []
for i in df.columns:
    if i not in lst:
        drop_cl.append(i)
# the column names in drop_cl are related to betting
df.drop(drop_cl, axis=1, inplace=True)
df.drop(3800, axis=0, inplace=True)
df.head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,E0506,13/08/05,Aston Villa,Bolton,2.0,2.0,D,2.0,2.0,D,...,2.0,6.0,14.0,16.0,7.0,8.0,0.0,2.0,0.0,0.0
1,E0506,13/08/05,Everton,Man United,0.0,2.0,A,0.0,1.0,A,...,5.0,5.0,15.0,14.0,8.0,6.0,3.0,1.0,0.0,0.0
2,E0506,13/08/05,Fulham,Birmingham,0.0,0.0,D,0.0,0.0,D,...,7.0,4.0,12.0,13.0,6.0,6.0,1.0,2.0,0.0,0.0
3,E0506,13/08/05,Man City,West Brom,0.0,0.0,D,0.0,0.0,D,...,8.0,3.0,13.0,11.0,3.0,6.0,2.0,3.0,0.0,0.0
4,E0506,13/08/05,Middlesbrough,Liverpool,0.0,0.0,D,0.0,0.0,D,...,2.0,7.0,17.0,11.0,5.0,0.0,2.0,3.0,1.0,0.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6460 entries, 0 to 6460
Data columns (total 23 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Div       6460 non-null   object
 1   Date      6460 non-null   object
 2   HomeTeam  6460 non-null   object
 3   AwayTeam  6460 non-null   object
 4   FTHG      6460 non-null   float64
 5   FTAG      6460 non-null   float64
 6   FTR       6460 non-null   object
 7   HTHG      6460 non-null   float64
 8   HTAG      6460 non-null   float64
 9   HTR       6460 non-null   object
 10  Referee   6460 non-null   object
 11  HS        6460 non-null   float64
 12  AS        6460 non-null   float64
 13  HST       6460 non-null   float64
 14  AST       6460 non-null   float64
 15  HF        6460 non-null   float64
 16  AF        6460 non-null   float64
 17  HC        6460 non-null   float64
 18  AC        6460 non-null   float64
 19  HY        6460 non-null   float64
 20  AY        6460 non-null   float64
 21  HR        6460 non-null   float64
 22  AR        6460 non-null   float64
dtypes: float64(16), object(7)
memory usage: 1.2+ MB

In [6]:
df.describe()

,FTHG,FTAG,HTHG,HTAG,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
count,6460.000000,6460.000000,6460.000000,6460.000000,6460.000000,6460.000000,6460.000000,6460.000000,6460.000000,6460.000000,6460.000000,6460.000000,6460.000000,6460.000000,6460.000000,6460.000000
mean,1.525232,1.168266,0.683127,0.513313,13.739938,10.975697,5.971981,4.738390,10.977554,11.372446,6.003406,4.787771,1.462074,1.760372,0.059907,0.086223
std,1.308971,1.157920,0.835277,0.731679,5.412867,4.717523,3.367787,2.824973,3.621377,3.771412,3.117504,2.745714,1.198111,1.274098,0.246297,0.291537
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,10.000000,8.000000,3.000000,3.000000,8.000000,9.000000,4.000000,3.000000,1.000000,1.000000,0.000000,0.000000
50%,1.000000,1.000000,0.000000,0.000000,13.000000,10.000000,5.000000,4.000000,11.000000,11.000000,6.000000,4.000000,1.000000,2.000000,0.000000,0.000000
75%,2.000000,2.000000,1.000000,1.000000,17.000000,14.000000,8.000000,6.000000,13.000000,14.000000,8.000000,6.000000,2.000000,3.000000,0.000000,0.000000
max,9.000000,9.000000,5.000000,5.000000,43.000000,31.000000,24.000000,20.000000,33.000000,26.000000,20.000000,19.000000,7.000000,9.000000,2.000000,2.000000

In [7]:
seasons = list(df['Div'].unique())
print(len(seasons))
seasons

17

['E0506',
 'E0607',
 'E0708',
 'E0809',
 'E0910',
 'E1011',
 'E1112',
 'E1213',
 'E1314',
 'E1415',
 'E1516',
 'E1617',
 'E1718',
 'E1819',
 'E1920',
 'E2021',
 'E2122']

In [8]:
teams = list(df['HomeTeam'].unique())
print(len(teams))
teams

41

['Aston Villa',
 'Everton',
 'Fulham',
 'Man City',
 'Middlesbrough',
 'Portsmouth',
 'Sunderland',
 'West Ham',
 'Arsenal',
 'Wigan',
 'Birmingham',
 'Blackburn',
 'Charlton',
 'Liverpool',
 'Man United',
 'Newcastle',
 'Tottenham',
 'West Brom',
 'Bolton',
 'Chelsea',
 'Reading',
 'Sheffield United',
 'Watford',
 'Derby',
 'Hull',
 'Stoke',
 'Wolves',
 'Burnley',
 'Blackpool',
 'QPR',
 'Swansea',
 'Norwich',
 'Southampton',
 'Crystal Palace',
 'Cardiff',
 'Leicester',
 'Bournemouth',
 'Brighton',
 'Huddersfield',
 'Leeds',
 'Brentford']

In [9]:
home_team_wins = {}
for i in teams:
    x = df[(df['HomeTeam']==i) & (df['FTR']=='H')]
    home_team_wins[i]=x.shape[0]
home_team_wins=dict(sorted(home_team_wins.items(), key = lambda x: x[1], reverse = True))
home_team_wins

{'Man City': 226,
 'Man United': 223,
 'Chelsea': 212,
 'Arsenal': 211,
 'Liverpool': 211,
 'Tottenham': 197,
 'Everton': 162,
 'West Ham': 127,
 'Newcastle': 115,
 'Aston Villa': 88,
 'Fulham': 85,
 'Stoke': 81,
 'Leicester': 74,
 'Southampton': 71,
 'West Brom': 68,
 'Sunderland': 62,
 'Blackburn': 59,
 'Crystal Palace': 57,
 'Bolton': 54,
 'Burnley': 52,
 'Swansea': 51,
 'Wigan': 48,
 'Wolves': 48,
 'Watford': 40,
 'Portsmouth': 36,
 'Norwich': 34,
 'Bournemouth': 34,
 'Middlesbrough': 33,
 'Hull': 29,
 'Brighton': 27,
 'Birmingham': 26,
 'Reading': 23,
 'Sheffield United': 22,
 'Charlton': 15,
 'QPR': 15,
 'Leeds': 12,
 'Cardiff': 11,
 'Huddersfield': 8,
 'Brentford': 7,
 'Blackpool': 5,
 'Derby': 1}

In [10]:
away_team_wins = {}
for i in teams:
    x = df[(df['AwayTeam']==i) & (df['FTR']=='A')]
    away_team_wins[i]=x.shape[0]
away_team_win=dict(sorted(away_team_wins.items(), key = lambda x: x[1], reverse = True))
away_team_win

{'Chelsea': 174,
 'Man United': 166,
 'Liverpool': 158,
 'Man City': 157,
 'Arsenal': 139,
 'Tottenham': 128,
 'Everton': 93,
 'West Ham': 76,
 'Aston Villa': 73,
 'Newcastle': 66,
 'Southampton': 53,
 'Crystal Palace': 51,
 'Leicester': 51,
 'Wigan': 37,
 'West Brom': 37,
 'Sunderland': 36,
 'Stoke': 35,
 'Wolves': 35,
 'Blackburn': 32,
 'Burnley': 31,
 'Swansea': 31,
 'Bolton': 29,
 'Fulham': 28,
 'Watford': 27,
 'Bournemouth': 22,
 'Portsmouth': 21,
 'Brighton': 21,
 'Norwich': 15,
 'Leeds': 15,
 'Middlesbrough': 13,
 'Hull': 12,
 'Birmingham': 11,
 'Reading': 9,
 'Sheffield United': 9,
 'QPR': 7,
 'Charlton': 6,
 'Cardiff': 6,
 'Brentford': 6,
 'Blackpool': 5,
 'Huddersfield': 4,
 'Derby': 0}

In [11]:
# total number of wins of each team
total_team_wins={}
for i in home_team_wins.keys():
    total_team_wins[i] = home_team_wins[i]+away_team_wins[i]
total_team_wins = dict(sorted(total_team_wins.items(), key = lambda x: x[1], reverse = True))
total_team_wins

{'Man United': 389,
 'Chelsea': 386,
 'Man City': 383,
 'Liverpool': 369,
 'Arsenal': 350,
 'Tottenham': 325,
 'Everton': 255,
 'West Ham': 203,
 'Newcastle': 181,
 'Aston Villa': 161,
 'Leicester': 125,
 'Southampton': 124,
 'Stoke': 116,
 'Fulham': 113,
 'Crystal Palace': 108,
 'West Brom': 105,
 'Sunderland': 98,
 'Blackburn': 91,
 'Wigan': 85,
 'Bolton': 83,
 'Burnley': 83,
 'Wolves': 83,
 'Swansea': 82,
 'Watford': 67,
 'Portsmouth': 57,
 'Bournemouth': 56,
 'Norwich': 49,
 'Brighton': 48,
 'Middlesbrough': 46,
 'Hull': 41,
 'Birmingham': 37,
 'Reading': 32,
 'Sheffield United': 31,
 'Leeds': 27,
 'QPR': 22,
 'Charlton': 21,
 'Cardiff': 17,
 'Brentford': 13,
 'Huddersfield': 12,
 'Blackpool': 10,
 'Derby': 1}

In [12]:
home_team_loss = {}
for i in teams:
    x = df[(df['HomeTeam']==i) & (df['FTR']=='A')]
    home_team_loss[i]=x.shape[0]
home_team_loss=dict(sorted(home_team_loss.items(), key = lambda x: x[1], reverse = True))
home_team_loss

{'West Ham': 106,
 'Aston Villa': 99,
 'Newcastle': 93,
 'Sunderland': 88,
 'West Brom': 88,
 'Everton': 81,
 'Fulham': 79,
 'Crystal Palace': 75,
 'Southampton': 65,
 'Tottenham': 62,
 'Burnley': 62,
 'Wigan': 59,
 'Watford': 57,
 'Stoke': 55,
 'Wolves': 54,
 'Man City': 52,
 'Norwich': 50,
 'Swansea': 45,
 'Leicester': 45,
 'Arsenal': 44,
 'Bolton': 44,
 'Man United': 42,
 'Hull': 42,
 'Blackburn': 40,
 'Chelsea': 36,
 'Bournemouth': 36,
 'Middlesbrough': 34,
 'Liverpool': 34,
 'Portsmouth': 33,
 'Brighton': 32,
 'Sheffield United': 25,
 'QPR': 24,
 'Reading': 22,
 'Huddersfield': 22,
 'Birmingham': 20,
 'Cardiff': 20,
 'Leeds': 15,
 'Charlton': 14,
 'Derby': 13,
 'Blackpool': 9,
 'Brentford': 9}

In [13]:
away_team_loss = {}
for i in teams:
    x = df[(df['AwayTeam']==i) & (df['FTR']=='H')]
    away_team_loss[i]=x.shape[0]
away_team_loss=dict(sorted(away_team_loss.items(), key = lambda x: x[1], reverse = True))
away_team_loss

{'Newcastle': 157,
 'West Ham': 150,
 'Everton': 128,
 'Aston Villa': 122,
 'Sunderland': 122,
 'Fulham': 113,
 'Tottenham': 110,
 'West Brom': 110,
 'Arsenal': 107,
 'Stoke': 100,
 'Man City': 98,
 'Liverpool': 90,
 'Southampton': 87,
 'Wigan': 84,
 'Chelsea': 83,
 'Burnley': 83,
 'Watford': 82,
 'Crystal Palace': 79,
 'Bolton': 77,
 'Man United': 76,
 'Norwich': 75,
 'Swansea': 73,
 'Blackburn': 70,
 'Leicester': 64,
 'Wolves': 63,
 'Hull': 59,
 'Middlesbrough': 55,
 'Bournemouth': 55,
 'Portsmouth': 53,
 'Birmingham': 48,
 'Brighton': 45,
 'QPR': 42,
 'Reading': 37,
 'Sheffield United': 36,
 'Cardiff': 26,
 'Huddersfield': 25,
 'Charlton': 23,
 'Leeds': 18,
 'Derby': 16,
 'Blackpool': 10,
 'Brentford': 9}

In [14]:
# total number of lost of each team
total_team_loss={}
for i in home_team_wins.keys():
    total_team_loss[i] = home_team_loss[i]+away_team_loss[i]
total_team_loss = dict(sorted(total_team_loss.items(), key = lambda x: x[1], reverse = True))
total_team_loss

{'West Ham': 256,
 'Newcastle': 250,
 'Aston Villa': 221,
 'Sunderland': 210,
 'Everton': 209,
 'West Brom': 198,
 'Fulham': 192,
 'Tottenham': 172,
 'Stoke': 155,
 'Crystal Palace': 154,
 'Southampton': 152,
 'Arsenal': 151,
 'Man City': 150,
 'Burnley': 145,
 'Wigan': 143,
 'Watford': 139,
 'Norwich': 125,
 'Liverpool': 124,
 'Bolton': 121,
 'Chelsea': 119,
 'Man United': 118,
 'Swansea': 118,
 'Wolves': 117,
 'Blackburn': 110,
 'Leicester': 109,
 'Hull': 101,
 'Bournemouth': 91,
 'Middlesbrough': 89,
 'Portsmouth': 86,
 'Brighton': 77,
 'Birmingham': 68,
 'QPR': 66,
 'Sheffield United': 61,
 'Reading': 59,
 'Huddersfield': 47,
 'Cardiff': 46,
 'Charlton': 37,
 'Leeds': 33,
 'Derby': 29,
 'Blackpool': 19,
 'Brentford': 18}

In [15]:
#total matches played by each team
total_matches = {}
for i in total_team_wins.keys():
    total_matches[i]=total_team_wins[i]+total_team_loss[i]
total_matches = dict(sorted(total_matches.items(), key = lambda x: x[1], reverse = True))
total_matches

{'Man City': 533,
 'Man United': 507,
 'Chelsea': 505,
 'Arsenal': 501,
 'Tottenham': 497,
 'Liverpool': 493,
 'Everton': 464,
 'West Ham': 459,
 'Newcastle': 431,
 'Aston Villa': 382,
 'Sunderland': 308,
 'Fulham': 305,
 'West Brom': 303,
 'Southampton': 276,
 'Stoke': 271,
 'Crystal Palace': 262,
 'Leicester': 234,
 'Wigan': 228,
 'Burnley': 228,
 'Watford': 206,
 'Bolton': 204,
 'Blackburn': 201,
 'Wolves': 200,
 'Swansea': 200,
 'Norwich': 174,
 'Bournemouth': 147,
 'Portsmouth': 143,
 'Hull': 142,
 'Middlesbrough': 135,
 'Brighton': 125,
 'Birmingham': 105,
 'Sheffield United': 92,
 'Reading': 91,
 'QPR': 88,
 'Cardiff': 63,
 'Leeds': 60,
 'Huddersfield': 59,
 'Charlton': 58,
 'Brentford': 31,
 'Derby': 30,
 'Blackpool': 29}

In [16]:
#teams which didnt play for seasons
teams_dict = {teams[i]: 0 for i in range(len(teams))}
for team in teams:
    for season in seasons:
        ht_data = df[(df['HomeTeam']==team) & (df['Div']==season)].shape[0]
        at_data = df[(df['AwayTeam']==team) & (df['Div']==season)].shape[0]
        matches = ht_data+at_data
        if matches == 0:
            teams_dict[team]+=1
teams_dict = dict(sorted(teams_dict.items(), key = lambda x: x[1], reverse = True))
teams_dict

{'Derby': 16,
 'Blackpool': 16,
 'Brentford': 16,
 'Charlton': 15,
 'Cardiff': 15,
 'Huddersfield': 15,
 'Leeds': 15,
 'Reading': 14,
 'Sheffield United': 14,
 'QPR': 14,
 'Birmingham': 13,
 'Middlesbrough': 12,
 'Portsmouth': 12,
 'Hull': 12,
 'Bournemouth': 12,
 'Brighton': 12,
 'Norwich': 11,
 'Blackburn': 10,
 'Bolton': 10,
 'Watford': 10,
 'Wolves': 10,
 'Swansea': 10,
 'Wigan': 9,
 'Burnley': 9,
 'Leicester': 9,
 'Crystal Palace': 8,
 'Stoke': 7,
 'Southampton': 7,
 'Fulham': 6,
 'Sunderland': 6,
 'West Brom': 6,
 'Aston Villa': 3,
 'Newcastle': 2,
 'West Ham': 1,
 'Everton': 0,
 'Man City': 0,
 'Arsenal': 0,
 'Liverpool': 0,
 'Man United': 0,
 'Tottenham': 0,
 'Chelsea': 0}

In [17]:
draws = df[df['FTR']=='D']
draws

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,E0506,13/08/05,Aston Villa,Bolton,2.0,2.0,D,2.0,2.0,D,...,2.0,6.0,14.0,16.0,7.0,8.0,0.0,2.0,0.0,0.0
2,E0506,13/08/05,Fulham,Birmingham,0.0,0.0,D,0.0,0.0,D,...,7.0,4.0,12.0,13.0,6.0,6.0,1.0,2.0,0.0,0.0
3,E0506,13/08/05,Man City,West Brom,0.0,0.0,D,0.0,0.0,D,...,8.0,3.0,13.0,11.0,3.0,6.0,2.0,3.0,0.0,0.0
4,E0506,13/08/05,Middlesbrough,Liverpool,0.0,0.0,D,0.0,0.0,D,...,2.0,7.0,17.0,11.0,5.0,0.0,2.0,3.0,1.0,0.0
15,E0506,20/08/05,Newcastle,West Ham,0.0,0.0,D,0.0,0.0,D,...,6.0,1.0,9.0,11.0,10.0,2.0,1.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6441,E2122,15/05/2022,Leeds,Brighton,1.0,1.0,D,0.0,1.0,A,...,5.0,6.0,16.0,8.0,8.0,1.0,3.0,2.0,0.0,0.0
6443,E2122,15/05/2022,West Ham,Man City,2.0,2.0,D,2.0,0.0,H,...,2.0,8.0,9.0,5.0,4.0,9.0,3.0,1.0,0.0,0.0
6444,E2122,15/05/2022,Wolves,Norwich,1.0,1.0,D,0.0,1.0,A,...,4.0,2.0,5.0,10.0,5.0,3.0,0.0,3.0,0.0,0.0
6449,E2122,19/05/2022,Aston Villa,Burnley,1.0,1.0,D,0.0,1.0,A,...,9.0,5.0,11.0,20.0,13.0,6.0,0.0,1.0,0.0,1.0
6450,E2122,19/05/2022,Chelsea,Leicester,1.0,1.0,D,1.0,1.0,D,...,7.0,1.0,13.0,7.0,6.0,0.0,4.0,1.0,0.0,0.0

In [18]:
homeTeam_draws = dict(sorted(dict(draws['HomeTeam'].value_counts()).items(), key = lambda x: x[1], reverse = True))
homeTeam_draws

{'Everton': 80,
 'Aston Villa': 79,
 'Liverpool': 78,
 'Newcastle': 77,
 'Chelsea': 75,
 'West Ham': 71,
 'Arsenal': 68,
 'Tottenham': 64,
 'Sunderland': 59,
 'Man United': 58,
 'Southampton': 54,
 'Stoke': 54,
 'West Brom': 53,
 'Wigan': 45,
 'Man City': 45,
 'Fulham': 45,
 'Crystal Palace': 39,
 'Burnley': 38,
 'Swansea': 37,
 'Brighton': 36,
 'Watford': 36,
 'Bolton': 35,
 'Blackburn': 34,
 'Leicester': 33,
 'Wolves': 31,
 'Norwich': 30,
 'Birmingham': 30,
 'Middlesbrough': 28,
 'Portsmouth': 26,
 'Bournemouth': 25,
 'Hull': 24,
 'QPR': 18,
 'Reading': 12,
 'Leeds': 11,
 'Sheffield United': 10,
 'Charlton': 9,
 'Huddersfield': 8,
 'Cardiff': 7,
 'Blackpool': 5,
 'Derby': 5,
 'Brentford': 3}

In [19]:
awayTeam_draws = dict(sorted(dict(draws['AwayTeam'].value_counts()).items(), key = lambda x: x[1], reverse = True))
awayTeam_draws

{'Everton': 102,
 'Tottenham': 85,
 'Man United': 81,
 'West Ham': 78,
 'Arsenal': 77,
 'Liverpool': 75,
 'Aston Villa': 71,
 'Man City': 68,
 'Fulham': 68,
 'Chelsea': 66,
 'Newcastle': 62,
 'West Brom': 62,
 'Stoke': 55,
 'Sunderland': 51,
 'Southampton': 50,
 'Crystal Palace': 41,
 'Burnley': 38,
 'Leicester': 37,
 'Wolves': 35,
 'Blackburn': 31,
 'Wigan': 31,
 'Brighton': 29,
 'Swansea': 29,
 'Middlesbrough': 27,
 'Bolton': 27,
 'Norwich': 24,
 'Watford': 24,
 'Hull': 24,
 'Portsmouth': 21,
 'Bournemouth': 18,
 'Birmingham': 17,
 'Sheffield United': 12,
 'Reading': 11,
 'Charlton': 9,
 'Huddersfield': 9,
 'QPR': 8,
 'Cardiff': 6,
 'Leeds': 5,
 'Blackpool': 4,
 'Brentford': 4,
 'Derby': 3}

In [20]:
# total number of draws of each team
totalTeam_draws = {}
for i in homeTeam_draws.keys():
    totalTeam_draws[i]=homeTeam_draws[i]+awayTeam_draws[i]
totalTeam_draws = dict(sorted(totalTeam_draws.items(), key = lambda x: x[1], reverse = True))
totalTeam_draws

{'Everton': 182,
 'Liverpool': 153,
 'Aston Villa': 150,
 'West Ham': 149,
 'Tottenham': 149,
 'Arsenal': 145,
 'Chelsea': 141,
 'Newcastle': 139,
 'Man United': 139,
 'West Brom': 115,
 'Man City': 113,
 'Fulham': 113,
 'Sunderland': 110,
 'Stoke': 109,
 'Southampton': 104,
 'Crystal Palace': 80,
 'Wigan': 76,
 'Burnley': 76,
 'Leicester': 70,
 'Swansea': 66,
 'Wolves': 66,
 'Brighton': 65,
 'Blackburn': 65,
 'Bolton': 62,
 'Watford': 60,
 'Middlesbrough': 55,
 'Norwich': 54,
 'Hull': 48,
 'Birmingham': 47,
 'Portsmouth': 47,
 'Bournemouth': 43,
 'QPR': 26,
 'Reading': 23,
 'Sheffield United': 22,
 'Charlton': 18,
 'Huddersfield': 17,
 'Leeds': 16,
 'Cardiff': 13,
 'Blackpool': 9,
 'Derby': 8,
 'Brentford': 7}

In [21]:
h_goals = {}
for i in teams:
    h_goals[i] = df[df['HomeTeam']==i]['FTHG'].sum()
h_goals = dict(sorted(h_goals.items(), key = lambda x: x[1], reverse = True))
h_goals

{'Man City': 742.0,
 'Liverpool': 683.0,
 'Man United': 675.0,
 'Chelsea': 675.0,
 'Arsenal': 664.0,
 'Tottenham': 596.0,
 'Everton': 522.0,
 'West Ham': 443.0,
 'Newcastle': 392.0,
 'Aston Villa': 333.0,
 'Fulham': 275.0,
 'Southampton': 270.0,
 'West Brom': 261.0,
 'Stoke': 248.0,
 'Leicester': 246.0,
 'Sunderland': 235.0,
 'Crystal Palace': 192.0,
 'Blackburn': 186.0,
 'Bolton': 182.0,
 'Swansea': 179.0,
 'Wigan': 169.0,
 'Burnley': 161.0,
 'Wolves': 158.0,
 'Watford': 156.0,
 'Bournemouth': 136.0,
 'Norwich': 127.0,
 'Middlesbrough': 120.0,
 'Portsmouth': 119.0,
 'Hull': 107.0,
 'Brighton': 104.0,
 'Birmingham': 87.0,
 'Reading': 71.0,
 'Sheffield United': 60.0,
 'QPR': 60.0,
 'Leeds': 47.0,
 'Charlton': 41.0,
 'Cardiff': 41.0,
 'Blackpool': 30.0,
 'Huddersfield': 26.0,
 'Brentford': 22.0,
 'Derby': 12.0}

In [22]:
a_goals = {}
for i in teams:
    a_goals[i] = df[df['AwayTeam']==i]['FTAG'].sum()
a_goals = dict(sorted(a_goals.items(), key = lambda x: x[1], reverse = True))
a_goals

{'Man City': 546.0,
 'Liverpool': 527.0,
 'Man United': 525.0,
 'Chelsea': 522.0,
 'Arsenal': 510.0,
 'Tottenham': 486.0,
 'Everton': 352.0,
 'West Ham': 330.0,
 'Aston Villa': 306.0,
 'Newcastle': 271.0,
 'Leicester': 220.0,
 'Southampton': 210.0,
 'Crystal Palace': 195.0,
 'Sunderland': 189.0,
 'West Brom': 184.0,
 'Fulham': 175.0,
 'Stoke': 150.0,
 'Wigan': 147.0,
 'Blackburn': 142.0,
 'Burnley': 139.0,
 'Wolves': 132.0,
 'Bolton': 131.0,
 'Swansea': 127.0,
 'Watford': 119.0,
 'Bournemouth': 105.0,
 'Brighton': 86.0,
 'Portsmouth': 83.0,
 'Norwich': 82.0,
 'Hull': 74.0,
 'Middlesbrough': 70.0,
 'Reading': 65.0,
 'Birmingham': 62.0,
 'Leeds': 57.0,
 'QPR': 55.0,
 'Charlton': 34.0,
 'Sheffield United': 31.0,
 'Brentford': 26.0,
 'Blackpool': 25.0,
 'Cardiff': 25.0,
 'Huddersfield': 24.0,
 'Derby': 8.0}

In [23]:
# total number of goals of each team
total_goals = {}
for i in teams:
    total_goals[i] = h_goals[i]+a_goals[i]
total_goals = dict(sorted(total_goals.items(), key = lambda x: x[1], reverse = True))
total_goals

{'Man City': 1288.0,
 'Liverpool': 1210.0,
 'Man United': 1200.0,
 'Chelsea': 1197.0,
 'Arsenal': 1174.0,
 'Tottenham': 1082.0,
 'Everton': 874.0,
 'West Ham': 773.0,
 'Newcastle': 663.0,
 'Aston Villa': 639.0,
 'Southampton': 480.0,
 'Leicester': 466.0,
 'Fulham': 450.0,
 'West Brom': 445.0,
 'Sunderland': 424.0,
 'Stoke': 398.0,
 'Crystal Palace': 387.0,
 'Blackburn': 328.0,
 'Wigan': 316.0,
 'Bolton': 313.0,
 'Swansea': 306.0,
 'Burnley': 300.0,
 'Wolves': 290.0,
 'Watford': 275.0,
 'Bournemouth': 241.0,
 'Norwich': 209.0,
 'Portsmouth': 202.0,
 'Middlesbrough': 190.0,
 'Brighton': 190.0,
 'Hull': 181.0,
 'Birmingham': 149.0,
 'Reading': 136.0,
 'QPR': 115.0,
 'Leeds': 104.0,
 'Sheffield United': 91.0,
 'Charlton': 75.0,
 'Cardiff': 66.0,
 'Blackpool': 55.0,
 'Huddersfield': 50.0,
 'Brentford': 48.0,
 'Derby': 20.0}

In [24]:
h_conceded = {}
for i in teams:
    h_conceded[i] = df[df['HomeTeam']==i]['FTAG'].sum()
h_conceded = dict(sorted(h_conceded.items(), key = lambda x: x[1], reverse = True))
h_conceded

{'West Ham': 414.0,
 'Newcastle': 367.0,
 'Everton': 355.0,
 'Aston Villa': 340.0,
 'Tottenham': 307.0,
 'West Brom': 303.0,
 'Fulham': 282.0,
 'Arsenal': 276.0,
 'Sunderland': 273.0,
 'Man City': 269.0,
 'Chelsea': 263.0,
 'Man United': 260.0,
 'Liverpool': 245.0,
 'Southampton': 243.0,
 'Crystal Palace': 217.0,
 'Wigan': 215.0,
 'Stoke': 213.0,
 'Watford': 205.0,
 'Burnley': 195.0,
 'Wolves': 185.0,
 'Norwich': 178.0,
 'Leicester': 177.0,
 'Swansea': 170.0,
 'Bolton': 166.0,
 'Blackburn': 151.0,
 'Bournemouth': 148.0,
 'Hull': 145.0,
 'Brighton': 125.0,
 'Middlesbrough': 120.0,
 'Portsmouth': 114.0,
 'Birmingham': 78.0,
 'Reading': 78.0,
 'QPR': 77.0,
 'Cardiff': 73.0,
 'Sheffield United': 63.0,
 'Leeds': 59.0,
 'Huddersfield': 56.0,
 'Derby': 43.0,
 'Charlton': 41.0,
 'Blackpool': 37.0,
 'Brentford': 21.0}

In [25]:
a_conceded = {}
for i in teams:
    a_conceded[i] = df[df['AwayTeam']==i]['FTHG'].sum()
a_conceded = dict(sorted(a_conceded.items(), key = lambda x: x[1], reverse = True))
a_conceded

{'Newcastle': 486.0,
 'West Ham': 480.0,
 'Tottenham': 437.0,
 'Aston Villa': 436.0,
 'Everton': 436.0,
 'Arsenal': 422.0,
 'Liverpool': 375.0,
 'Man City': 365.0,
 'Sunderland': 365.0,
 'Man United': 351.0,
 'Fulham': 349.0,
 'West Brom': 343.0,
 'Chelsea': 328.0,
 'Stoke': 312.0,
 'Southampton': 301.0,
 'Wigan': 267.0,
 'Crystal Palace': 266.0,
 'Burnley': 260.0,
 'Blackburn': 245.0,
 'Watford': 236.0,
 'Leicester': 235.0,
 'Bolton': 234.0,
 'Norwich': 234.0,
 'Swansea': 213.0,
 'Wolves': 200.0,
 'Bournemouth': 182.0,
 'Hull': 178.0,
 'Portsmouth': 153.0,
 'Middlesbrough': 150.0,
 'Birmingham': 139.0,
 'Brighton': 133.0,
 'QPR': 122.0,
 'Reading': 108.0,
 'Sheffield United': 94.0,
 'Huddersfield': 78.0,
 'Charlton': 74.0,
 'Leeds': 74.0,
 'Cardiff': 70.0,
 'Derby': 46.0,
 'Blackpool': 41.0,
 'Brentford': 35.0}

In [26]:
# total number of conceded of each team
conceded = {}
for i in teams:
    conceded[i] = h_conceded[i] + a_conceded[i]

conceded = dict(sorted(conceded.items(), key = lambda x: x[1], reverse = True))
conceded

{'West Ham': 894.0,
 'Newcastle': 853.0,
 'Everton': 791.0,
 'Aston Villa': 776.0,
 'Tottenham': 744.0,
 'Arsenal': 698.0,
 'West Brom': 646.0,
 'Sunderland': 638.0,
 'Man City': 634.0,
 'Fulham': 631.0,
 'Liverpool': 620.0,
 'Man United': 611.0,
 'Chelsea': 591.0,
 'Southampton': 544.0,
 'Stoke': 525.0,
 'Crystal Palace': 483.0,
 'Wigan': 482.0,
 'Burnley': 455.0,
 'Watford': 441.0,
 'Norwich': 412.0,
 'Leicester': 412.0,
 'Bolton': 400.0,
 'Blackburn': 396.0,
 'Wolves': 385.0,
 'Swansea': 383.0,
 'Bournemouth': 330.0,
 'Hull': 323.0,
 'Middlesbrough': 270.0,
 'Portsmouth': 267.0,
 'Brighton': 258.0,
 'Birmingham': 217.0,
 'QPR': 199.0,
 'Reading': 186.0,
 'Sheffield United': 157.0,
 'Cardiff': 143.0,
 'Huddersfield': 134.0,
 'Leeds': 133.0,
 'Charlton': 115.0,
 'Derby': 89.0,
 'Blackpool': 78.0,
 'Brentford': 56.0}

In [27]:
h_shots = {}
for i in teams:
    h_shots[i] = df[df['HomeTeam']==i]['HS'].sum()
h_shots = dict(sorted(h_shots.items(), key = lambda x: x[1], reverse = True))
h_shots

{'Liverpool': 5804.0,
 'Chelsea': 5506.0,
 'Man City': 5337.0,
 'Man United': 5268.0,
 'Tottenham': 5204.0,
 'Arsenal': 5095.0,
 'Everton': 4378.0,
 'West Ham': 3893.0,
 'Newcastle': 3734.0,
 'Aston Villa': 3216.0,
 'Southampton': 2643.0,
 'Fulham': 2616.0,
 'West Brom': 2564.0,
 'Sunderland': 2486.0,
 'Stoke': 2181.0,
 'Crystal Palace': 2122.0,
 'Leicester': 2059.0,
 'Wigan': 1986.0,
 'Burnley': 1721.0,
 'Bolton': 1710.0,
 'Wolves': 1656.0,
 'Swansea': 1647.0,
 'Blackburn': 1646.0,
 'Watford': 1594.0,
 'Norwich': 1388.0,
 'Portsmouth': 1360.0,
 'Brighton': 1228.0,
 'Bournemouth': 1191.0,
 'Hull': 1106.0,
 'Middlesbrough': 1087.0,
 'QPR': 843.0,
 'Birmingham': 793.0,
 'Sheffield United': 620.0,
 'Reading': 570.0,
 'Leeds': 529.0,
 'Cardiff': 458.0,
 'Charlton': 432.0,
 'Huddersfield': 410.0,
 'Blackpool': 253.0,
 'Brentford': 233.0,
 'Derby': 193.0}

In [28]:
a_shots = {}
for i in teams:
    a_shots[i] = df[df['AwayTeam']==i]['AS'].sum()
a_shots = dict(sorted(a_shots.items(), key = lambda x: x[1], reverse = True))
a_shots

{'Chelsea': 4549.0,
 'Man City': 4545.0,
 'Liverpool': 4491.0,
 'Man United': 4082.0,
 'Arsenal': 4063.0,
 'Tottenham': 4009.0,
 'Everton': 3487.0,
 'West Ham': 3170.0,
 'Newcastle': 2760.0,
 'Aston Villa': 2696.0,
 'Southampton': 2270.0,
 'West Brom': 2082.0,
 'Fulham': 2000.0,
 'Sunderland': 1997.0,
 'Leicester': 1746.0,
 'Crystal Palace': 1737.0,
 'Stoke': 1700.0,
 'Wigan': 1602.0,
 'Burnley': 1421.0,
 'Swansea': 1317.0,
 'Watford': 1308.0,
 'Wolves': 1300.0,
 'Bolton': 1278.0,
 'Blackburn': 1242.0,
 'Norwich': 1120.0,
 'Bournemouth': 1021.0,
 'Brighton': 958.0,
 'Portsmouth': 913.0,
 'Hull': 896.0,
 'Middlesbrough': 880.0,
 'QPR': 649.0,
 'Birmingham': 610.0,
 'Reading': 503.0,
 'Leeds': 478.0,
 'Sheffield United': 461.0,
 'Cardiff': 378.0,
 'Huddersfield': 350.0,
 'Charlton': 290.0,
 'Brentford': 209.0,
 'Blackpool': 193.0,
 'Derby': 142.0}

In [29]:
# total number of shots of each team
total_shots = {}
for i in teams:
    total_shots[i] = h_shots[i]+a_shots[i]
total_shots = dict(sorted(total_shots.items(), key = lambda x: x[1], reverse = True))
total_shots

{'Liverpool': 10295.0,
 'Chelsea': 10055.0,
 'Man City': 9882.0,
 'Man United': 9350.0,
 'Tottenham': 9213.0,
 'Arsenal': 9158.0,
 'Everton': 7865.0,
 'West Ham': 7063.0,
 'Newcastle': 6494.0,
 'Aston Villa': 5912.0,
 'Southampton': 4913.0,
 'West Brom': 4646.0,
 'Fulham': 4616.0,
 'Sunderland': 4483.0,
 'Stoke': 3881.0,
 'Crystal Palace': 3859.0,
 'Leicester': 3805.0,
 'Wigan': 3588.0,
 'Burnley': 3142.0,
 'Bolton': 2988.0,
 'Swansea': 2964.0,
 'Wolves': 2956.0,
 'Watford': 2902.0,
 'Blackburn': 2888.0,
 'Norwich': 2508.0,
 'Portsmouth': 2273.0,
 'Bournemouth': 2212.0,
 'Brighton': 2186.0,
 'Hull': 2002.0,
 'Middlesbrough': 1967.0,
 'QPR': 1492.0,
 'Birmingham': 1403.0,
 'Sheffield United': 1081.0,
 'Reading': 1073.0,
 'Leeds': 1007.0,
 'Cardiff': 836.0,
 'Huddersfield': 760.0,
 'Charlton': 722.0,
 'Blackpool': 446.0,
 'Brentford': 442.0,
 'Derby': 335.0}

In [30]:
h_sot = {}
for i in teams:
    h_sot[i] = df[df['HomeTeam']==i]['HST'].sum()
h_sot = dict(sorted(h_sot.items(), key = lambda x: x[1], reverse = True))
h_sot

{'Liverpool': 2517.0,
 'Man United': 2504.0,
 'Chelsea': 2487.0,
 'Tottenham': 2424.0,
 'Arsenal': 2413.0,
 'Man City': 2364.0,
 'Everton': 1942.0,
 'West Ham': 1649.0,
 'Newcastle': 1598.0,
 'Aston Villa': 1391.0,
 'Fulham': 1292.0,
 'Sunderland': 1113.0,
 'West Brom': 1094.0,
 'Wigan': 1024.0,
 'Bolton': 982.0,
 'Southampton': 951.0,
 'Stoke': 854.0,
 'Blackburn': 835.0,
 'Portsmouth': 735.0,
 'Leicester': 705.0,
 'Crystal Palace': 691.0,
 'Wolves': 690.0,
 'Swansea': 678.0,
 'Burnley': 600.0,
 'Norwich': 545.0,
 'Middlesbrough': 540.0,
 'Watford': 529.0,
 'Hull': 438.0,
 'Bournemouth': 399.0,
 'Birmingham': 393.0,
 'QPR': 356.0,
 'Brighton': 339.0,
 'Reading': 297.0,
 'Sheffield United': 251.0,
 'Charlton': 207.0,
 'Leeds': 182.0,
 'Cardiff': 142.0,
 'Blackpool': 134.0,
 'Huddersfield': 112.0,
 'Derby': 105.0,
 'Brentford': 77.0}

In [31]:
a_sot = {}
for i in teams:
    a_sot[i] = df[df['AwayTeam']==i]['AST'].sum()
a_sot = dict(sorted(a_sot.items(), key = lambda x: x[1], reverse = True))
a_sot

{'Liverpool': 2006.0,
 'Chelsea': 1968.0,
 'Man City': 1951.0,
 'Man United': 1909.0,
 'Tottenham': 1845.0,
 'Arsenal': 1843.0,
 'Everton': 1563.0,
 'West Ham': 1315.0,
 'Aston Villa': 1242.0,
 'Newcastle': 1194.0,
 'Fulham': 944.0,
 'Sunderland': 919.0,
 'West Brom': 858.0,
 'Wigan': 841.0,
 'Southampton': 822.0,
 'Blackburn': 679.0,
 'Bolton': 659.0,
 'Stoke': 646.0,
 'Leicester': 634.0,
 'Crystal Palace': 576.0,
 'Wolves': 538.0,
 'Swansea': 521.0,
 'Burnley': 504.0,
 'Portsmouth': 473.0,
 'Watford': 453.0,
 'Norwich': 424.0,
 'Middlesbrough': 421.0,
 'Bournemouth': 347.0,
 'Hull': 343.0,
 'Birmingham': 339.0,
 'Brighton': 324.0,
 'QPR': 304.0,
 'Reading': 243.0,
 'Leeds': 171.0,
 'Sheffield United': 165.0,
 'Charlton': 144.0,
 'Huddersfield': 117.0,
 'Cardiff': 110.0,
 'Blackpool': 101.0,
 'Derby': 77.0,
 'Brentford': 77.0}

In [32]:
# total number of shots on target of each team
total_sot = {}
for i in teams:
    total_sot[i] = h_sot[i]+a_sot[i]
total_sot = dict(sorted(total_sot.items(), key = lambda x: x[1], reverse = True))
total_sot

{'Liverpool': 4523.0,
 'Chelsea': 4455.0,
 'Man United': 4413.0,
 'Man City': 4315.0,
 'Tottenham': 4269.0,
 'Arsenal': 4256.0,
 'Everton': 3505.0,
 'West Ham': 2964.0,
 'Newcastle': 2792.0,
 'Aston Villa': 2633.0,
 'Fulham': 2236.0,
 'Sunderland': 2032.0,
 'West Brom': 1952.0,
 'Wigan': 1865.0,
 'Southampton': 1773.0,
 'Bolton': 1641.0,
 'Blackburn': 1514.0,
 'Stoke': 1500.0,
 'Leicester': 1339.0,
 'Crystal Palace': 1267.0,
 'Wolves': 1228.0,
 'Portsmouth': 1208.0,
 'Swansea': 1199.0,
 'Burnley': 1104.0,
 'Watford': 982.0,
 'Norwich': 969.0,
 'Middlesbrough': 961.0,
 'Hull': 781.0,
 'Bournemouth': 746.0,
 'Birmingham': 732.0,
 'Brighton': 663.0,
 'QPR': 660.0,
 'Reading': 540.0,
 'Sheffield United': 416.0,
 'Leeds': 353.0,
 'Charlton': 351.0,
 'Cardiff': 252.0,
 'Blackpool': 235.0,
 'Huddersfield': 229.0,
 'Derby': 182.0,
 'Brentford': 154.0}

In [33]:
h_corners = {}
for i in teams:
    h_corners[i] = df[df['HomeTeam']==i]['HC'].sum()
h_corners = dict(sorted(h_corners.items(), key = lambda x: x[1], reverse = True))
h_corners

{'Liverpool': 2413.0,
 'Man City': 2393.0,
 'Arsenal': 2338.0,
 'Chelsea': 2225.0,
 'Tottenham': 2165.0,
 'Man United': 2132.0,
 'Everton': 1976.0,
 'West Ham': 1691.0,
 'Aston Villa': 1608.0,
 'Newcastle': 1547.0,
 'West Brom': 1145.0,
 'Fulham': 1125.0,
 'Southampton': 1102.0,
 'Sunderland': 1095.0,
 'Stoke': 1002.0,
 'Crystal Palace': 950.0,
 'Wigan': 870.0,
 'Leicester': 864.0,
 'Bolton': 785.0,
 'Wolves': 759.0,
 'Burnley': 732.0,
 'Swansea': 724.0,
 'Blackburn': 710.0,
 'Watford': 643.0,
 'Portsmouth': 626.0,
 'Norwich': 589.0,
 'Middlesbrough': 560.0,
 'Bournemouth': 540.0,
 'Brighton': 525.0,
 'Hull': 459.0,
 'Birmingham': 429.0,
 'Reading': 382.0,
 'Sheffield United': 345.0,
 'QPR': 285.0,
 'Leeds': 214.0,
 'Cardiff': 205.0,
 'Huddersfield': 187.0,
 'Charlton': 178.0,
 'Blackpool': 94.0,
 'Brentford': 88.0,
 'Derby': 82.0}

In [34]:
a_corners = {}
for i in teams:
    a_corners[i] = df[df['AwayTeam']==i]['AC'].sum()
a_corners = dict(sorted(a_corners.items(), key = lambda x: x[1], reverse = True))
a_corners

{'Man City': 1904.0,
 'Liverpool': 1902.0,
 'Chelsea': 1847.0,
 'Man United': 1798.0,
 'Tottenham': 1710.0,
 'Arsenal': 1693.0,
 'Everton': 1523.0,
 'West Ham': 1410.0,
 'Aston Villa': 1314.0,
 'Newcastle': 1187.0,
 'Southampton': 993.0,
 'West Brom': 892.0,
 'Sunderland': 857.0,
 'Fulham': 852.0,
 'Leicester': 775.0,
 'Crystal Palace': 770.0,
 'Stoke': 710.0,
 'Wolves': 660.0,
 'Blackburn': 642.0,
 'Bolton': 639.0,
 'Wigan': 638.0,
 'Burnley': 601.0,
 'Watford': 588.0,
 'Swansea': 557.0,
 'Bournemouth': 475.0,
 'Norwich': 463.0,
 'Portsmouth': 405.0,
 'Brighton': 393.0,
 'Hull': 388.0,
 'Middlesbrough': 347.0,
 'Birmingham': 325.0,
 'Reading': 325.0,
 'QPR': 259.0,
 'Sheffield United': 218.0,
 'Leeds': 188.0,
 'Cardiff': 159.0,
 'Charlton': 145.0,
 'Huddersfield': 140.0,
 'Blackpool': 92.0,
 'Derby': 74.0,
 'Brentford': 71.0}

In [35]:
# total number of corners of each team
total_corners = {}
for i in teams:
    total_corners[i] = h_corners[i]+a_corners[i]
total_corners = dict(sorted(total_corners.items(), key = lambda x: x[1], reverse = True))
total_corners

{'Liverpool': 4315.0,
 'Man City': 4297.0,
 'Chelsea': 4072.0,
 'Arsenal': 4031.0,
 'Man United': 3930.0,
 'Tottenham': 3875.0,
 'Everton': 3499.0,
 'West Ham': 3101.0,
 'Aston Villa': 2922.0,
 'Newcastle': 2734.0,
 'Southampton': 2095.0,
 'West Brom': 2037.0,
 'Fulham': 1977.0,
 'Sunderland': 1952.0,
 'Crystal Palace': 1720.0,
 'Stoke': 1712.0,
 'Leicester': 1639.0,
 'Wigan': 1508.0,
 'Bolton': 1424.0,
 'Wolves': 1419.0,
 'Blackburn': 1352.0,
 'Burnley': 1333.0,
 'Swansea': 1281.0,
 'Watford': 1231.0,
 'Norwich': 1052.0,
 'Portsmouth': 1031.0,
 'Bournemouth': 1015.0,
 'Brighton': 918.0,
 'Middlesbrough': 907.0,
 'Hull': 847.0,
 'Birmingham': 754.0,
 'Reading': 707.0,
 'Sheffield United': 563.0,
 'QPR': 544.0,
 'Leeds': 402.0,
 'Cardiff': 364.0,
 'Huddersfield': 327.0,
 'Charlton': 323.0,
 'Blackpool': 186.0,
 'Brentford': 159.0,
 'Derby': 156.0}

In [36]:
h_fouls = {}
for i in teams:
    h_fouls[i] = df[df['HomeTeam']==i]['HF'].sum()
h_fouls = dict(sorted(h_fouls.items(), key = lambda x: x[1], reverse = True))
h_fouls

{'Everton': 3617.0,
 'Man United': 3494.0,
 'Chelsea': 3418.0,
 'Man City': 3411.0,
 'Tottenham': 3355.0,
 'Arsenal': 3328.0,
 'West Ham': 3316.0,
 'Newcastle': 3234.0,
 'Liverpool': 3195.0,
 'Aston Villa': 3062.0,
 'Sunderland': 2368.0,
 'Fulham': 2291.0,
 'West Brom': 2289.0,
 'Stoke': 2191.0,
 'Southampton': 2061.0,
 'Crystal Palace': 1933.0,
 'Blackburn': 1814.0,
 'Wigan': 1804.0,
 'Bolton': 1684.0,
 'Watford': 1666.0,
 'Burnley': 1576.0,
 'Leicester': 1563.0,
 'Wolves': 1392.0,
 'Swansea': 1280.0,
 'Portsmouth': 1196.0,
 'Hull': 1180.0,
 'Middlesbrough': 1133.0,
 'Norwich': 1133.0,
 'Brighton': 1041.0,
 'Bournemouth': 872.0,
 'Birmingham': 853.0,
 'Sheffield United': 646.0,
 'QPR': 602.0,
 'Reading': 583.0,
 'Charlton': 474.0,
 'Leeds': 463.0,
 'Huddersfield': 394.0,
 'Cardiff': 362.0,
 'Derby': 238.0,
 'Blackpool': 216.0,
 'Brentford': 187.0}

In [37]:
a_fouls = {}
for i in teams:
    a_fouls[i] = df[df['AwayTeam']==i]['AF'].sum()
a_fouls = dict(sorted(a_fouls.items(), key = lambda x: x[1], reverse = True))
a_fouls

{'Everton': 3804.0,
 'Man United': 3674.0,
 'Liverpool': 3518.0,
 'Tottenham': 3518.0,
 'Man City': 3515.0,
 'Chelsea': 3455.0,
 'West Ham': 3431.0,
 'Arsenal': 3311.0,
 'Aston Villa': 3238.0,
 'Newcastle': 3198.0,
 'Sunderland': 2472.0,
 'Fulham': 2415.0,
 'West Brom': 2348.0,
 'Stoke': 2278.0,
 'Southampton': 2186.0,
 'Crystal Palace': 1992.0,
 'Wigan': 1886.0,
 'Bolton': 1765.0,
 'Blackburn': 1719.0,
 'Watford': 1671.0,
 'Leicester': 1656.0,
 'Burnley': 1589.0,
 'Wolves': 1479.0,
 'Swansea': 1357.0,
 'Middlesbrough': 1294.0,
 'Portsmouth': 1245.0,
 'Norwich': 1202.0,
 'Hull': 1148.0,
 'Brighton': 1040.0,
 'Birmingham': 933.0,
 'Bournemouth': 903.0,
 'Sheffield United': 678.0,
 'Reading': 634.0,
 'QPR': 618.0,
 'Charlton': 440.0,
 'Leeds': 433.0,
 'Huddersfield': 422.0,
 'Cardiff': 364.0,
 'Derby': 266.0,
 'Blackpool': 187.0,
 'Brentford': 184.0}

In [38]:
# total number of fouls commited of each team
total_fouls = {}
for i in teams:
    total_fouls[i] = h_fouls[i]+a_fouls[i]
total_fouls = dict(sorted(total_fouls.items(), key = lambda x: x[1], reverse = True))
total_fouls

{'Everton': 7421.0,
 'Man United': 7168.0,
 'Man City': 6926.0,
 'Tottenham': 6873.0,
 'Chelsea': 6873.0,
 'West Ham': 6747.0,
 'Liverpool': 6713.0,
 'Arsenal': 6639.0,
 'Newcastle': 6432.0,
 'Aston Villa': 6300.0,
 'Sunderland': 4840.0,
 'Fulham': 4706.0,
 'West Brom': 4637.0,
 'Stoke': 4469.0,
 'Southampton': 4247.0,
 'Crystal Palace': 3925.0,
 'Wigan': 3690.0,
 'Blackburn': 3533.0,
 'Bolton': 3449.0,
 'Watford': 3337.0,
 'Leicester': 3219.0,
 'Burnley': 3165.0,
 'Wolves': 2871.0,
 'Swansea': 2637.0,
 'Portsmouth': 2441.0,
 'Middlesbrough': 2427.0,
 'Norwich': 2335.0,
 'Hull': 2328.0,
 'Brighton': 2081.0,
 'Birmingham': 1786.0,
 'Bournemouth': 1775.0,
 'Sheffield United': 1324.0,
 'QPR': 1220.0,
 'Reading': 1217.0,
 'Charlton': 914.0,
 'Leeds': 896.0,
 'Huddersfield': 816.0,
 'Cardiff': 726.0,
 'Derby': 504.0,
 'Blackpool': 403.0,
 'Brentford': 371.0}

In [39]:
h_yellow = {}
for i in teams:
    h_yellow[i] = df[df['HomeTeam']==i]['HY'].sum()
h_yellow = dict(sorted(h_yellow.items(), key = lambda x: x[1], reverse = True))
h_yellow

{'Everton': 467.0,
 'West Ham': 464.0,
 'Arsenal': 463.0,
 'Man United': 457.0,
 'Tottenham': 443.0,
 'Newcastle': 439.0,
 'Chelsea': 429.0,
 'Man City': 411.0,
 'Aston Villa': 401.0,
 'Sunderland': 358.0,
 'Liverpool': 334.0,
 'Stoke': 317.0,
 'West Brom': 314.0,
 'Fulham': 286.0,
 'Crystal Palace': 271.0,
 'Watford': 261.0,
 'Southampton': 260.0,
 'Burnley': 236.0,
 'Wigan': 229.0,
 'Blackburn': 226.0,
 'Wolves': 204.0,
 'Bolton': 189.0,
 'Swansea': 188.0,
 'Leicester': 187.0,
 'Norwich': 172.0,
 'Brighton': 158.0,
 'Middlesbrough': 157.0,
 'Bournemouth': 152.0,
 'Portsmouth': 144.0,
 'Hull': 143.0,
 'Birmingham': 113.0,
 'Sheffield United': 93.0,
 'QPR': 87.0,
 'Leeds': 86.0,
 'Reading': 65.0,
 'Cardiff': 58.0,
 'Huddersfield': 53.0,
 'Charlton': 52.0,
 'Brentford': 29.0,
 'Derby': 27.0,
 'Blackpool': 22.0}

In [40]:
a_yellow = {}
for i in teams:
    a_yellow[i] = df[df['AwayTeam']==i]['AY'].sum()
a_yellow = dict(sorted(a_yellow.items(), key = lambda x: x[1], reverse = True))
a_yellow

{'Man United': 614.0,
 'Man City': 596.0,
 'Chelsea': 579.0,
 'Tottenham': 555.0,
 'Arsenal': 551.0,
 'West Ham': 549.0,
 'Everton': 535.0,
 'Liverpool': 528.0,
 'Aston Villa': 525.0,
 'Newcastle': 519.0,
 'Sunderland': 411.0,
 'Stoke': 371.0,
 'West Brom': 361.0,
 'Fulham': 326.0,
 'Southampton': 317.0,
 'Crystal Palace': 297.0,
 'Wigan': 289.0,
 'Bolton': 287.0,
 'Blackburn': 273.0,
 'Burnley': 273.0,
 'Leicester': 245.0,
 'Wolves': 228.0,
 'Watford': 216.0,
 'Norwich': 192.0,
 'Hull': 187.0,
 'Swansea': 182.0,
 'Middlesbrough': 176.0,
 'Portsmouth': 151.0,
 'Birmingham': 140.0,
 'Bournemouth': 139.0,
 'Brighton': 128.0,
 'Sheffield United': 109.0,
 'QPR': 104.0,
 'Reading': 81.0,
 'Leeds': 75.0,
 'Huddersfield': 63.0,
 'Cardiff': 56.0,
 'Charlton': 52.0,
 'Derby': 35.0,
 'Brentford': 32.0,
 'Blackpool': 25.0}

In [41]:
# total number of yellow cards of each team
total_yellow = {}
for i in teams:
    total_yellow[i] = h_yellow[i]+a_yellow[i]
total_yellow = dict(sorted(total_yellow.items(), key = lambda x: x[1], reverse = True))
total_yellow

{'Man United': 1071.0,
 'Arsenal': 1014.0,
 'West Ham': 1013.0,
 'Chelsea': 1008.0,
 'Man City': 1007.0,
 'Everton': 1002.0,
 'Tottenham': 998.0,
 'Newcastle': 958.0,
 'Aston Villa': 926.0,
 'Liverpool': 862.0,
 'Sunderland': 769.0,
 'Stoke': 688.0,
 'West Brom': 675.0,
 'Fulham': 612.0,
 'Southampton': 577.0,
 'Crystal Palace': 568.0,
 'Wigan': 518.0,
 'Burnley': 509.0,
 'Blackburn': 499.0,
 'Watford': 477.0,
 'Bolton': 476.0,
 'Wolves': 432.0,
 'Leicester': 432.0,
 'Swansea': 370.0,
 'Norwich': 364.0,
 'Middlesbrough': 333.0,
 'Hull': 330.0,
 'Portsmouth': 295.0,
 'Bournemouth': 291.0,
 'Brighton': 286.0,
 'Birmingham': 253.0,
 'Sheffield United': 202.0,
 'QPR': 191.0,
 'Leeds': 161.0,
 'Reading': 146.0,
 'Huddersfield': 116.0,
 'Cardiff': 114.0,
 'Charlton': 104.0,
 'Derby': 62.0,
 'Brentford': 61.0,
 'Blackpool': 47.0}

In [42]:
h_red = {}
for i in teams:
    h_red[i] = df[df['HomeTeam']==i]['HR'].sum()
h_red = dict(sorted(h_red.items(), key = lambda x: x[1], reverse = True))
h_red

{'Everton': 23.0,
 'Newcastle': 21.0,
 'Chelsea': 21.0,
 'Arsenal': 20.0,
 'Man City': 19.0,
 'Aston Villa': 18.0,
 'Southampton': 17.0,
 'Blackburn': 16.0,
 'Fulham': 15.0,
 'West Ham': 14.0,
 'Stoke': 14.0,
 'Sunderland': 13.0,
 'Watford': 13.0,
 'Tottenham': 12.0,
 'Hull': 12.0,
 'Liverpool': 11.0,
 'Man United': 11.0,
 'West Brom': 11.0,
 'Portsmouth': 10.0,
 'Wigan': 9.0,
 'Bolton': 9.0,
 'QPR': 9.0,
 'Leicester': 8.0,
 'Birmingham': 7.0,
 'Swansea': 6.0,
 'Norwich': 6.0,
 'Reading': 5.0,
 'Wolves': 5.0,
 'Crystal Palace': 5.0,
 'Bournemouth': 5.0,
 'Brighton': 5.0,
 'Huddersfield': 5.0,
 'Charlton': 3.0,
 'Middlesbrough': 2.0,
 'Sheffield United': 2.0,
 'Leeds': 2.0,
 'Brentford': 2.0,
 'Derby': 1.0,
 'Burnley': 0.0,
 'Blackpool': 0.0,
 'Cardiff': 0.0}

In [43]:
a_red = {}
for i in teams:
    a_red[i] = df[df['AwayTeam']==i]['AR'].sum()
a_red = dict(sorted(a_red.items(), key = lambda x: x[1], reverse = True))
a_red

{'Arsenal': 38.0,
 'Newcastle': 33.0,
 'Sunderland': 31.0,
 'Chelsea': 31.0,
 'Tottenham': 30.0,
 'Everton': 29.0,
 'Man City': 29.0,
 'West Ham': 28.0,
 'Man United': 27.0,
 'Liverpool': 21.0,
 'Wigan': 18.0,
 'Blackburn': 18.0,
 'Aston Villa': 16.0,
 'Stoke': 16.0,
 'West Brom': 15.0,
 'Bolton': 14.0,
 'Leicester': 14.0,
 'Hull': 12.0,
 'Watford': 11.0,
 'Brighton': 11.0,
 'Wolves': 10.0,
 'Southampton': 10.0,
 'Middlesbrough': 9.0,
 'Burnley': 9.0,
 'Crystal Palace': 9.0,
 'Fulham': 8.0,
 'Swansea': 8.0,
 'Norwich': 8.0,
 'Birmingham': 7.0,
 'QPR': 6.0,
 'Portsmouth': 5.0,
 'Sheffield United': 5.0,
 'Charlton': 4.0,
 'Reading': 4.0,
 'Bournemouth': 4.0,
 'Blackpool': 2.0,
 'Cardiff': 2.0,
 'Huddersfield': 2.0,
 'Leeds': 2.0,
 'Brentford': 1.0,
 'Derby': 0.0}

In [44]:
# total number of red cards of each team
total_red = {}
for i in teams:
    total_red[i] = h_red[i]+a_red[i]
total_red = dict(sorted(total_red.items(), key = lambda x: x[1], reverse = True))
total_red

{'Arsenal': 58.0,
 'Newcastle': 54.0,
 'Everton': 52.0,
 'Chelsea': 52.0,
 'Man City': 48.0,
 'Sunderland': 44.0,
 'West Ham': 42.0,
 'Tottenham': 42.0,
 'Man United': 38.0,
 'Aston Villa': 34.0,
 'Blackburn': 34.0,
 'Liverpool': 32.0,
 'Stoke': 30.0,
 'Wigan': 27.0,
 'Southampton': 27.0,
 'West Brom': 26.0,
 'Watford': 24.0,
 'Hull': 24.0,
 'Fulham': 23.0,
 'Bolton': 23.0,
 'Leicester': 22.0,
 'Brighton': 16.0,
 'Portsmouth': 15.0,
 'Wolves': 15.0,
 'QPR': 15.0,
 'Birmingham': 14.0,
 'Swansea': 14.0,
 'Norwich': 14.0,
 'Crystal Palace': 14.0,
 'Middlesbrough': 11.0,
 'Reading': 9.0,
 'Burnley': 9.0,
 'Bournemouth': 9.0,
 'Charlton': 7.0,
 'Sheffield United': 7.0,
 'Huddersfield': 7.0,
 'Leeds': 4.0,
 'Brentford': 3.0,
 'Blackpool': 2.0,
 'Cardiff': 2.0,
 'Derby': 1.0}

In [45]:
referee = dict(sorted(dict(df['Referee'].value_counts()).items(), key = lambda x: x[1], reverse = True))
referee

{'M Dean': 476,
 'M Atkinson': 456,
 'A Marriner': 375,
 'M Oliver': 320,
 'A Taylor': 314,
 'L Mason': 287,
 'M Clattenburg': 276,
 'J Moss': 274,
 'K Friend': 272,
 'H Webb': 266,
 'P Dowd': 250,
 'C Foy': 227,
 'C Pawson': 206,
 'M Jones': 202,
 'L Probert': 182,
 'M Halsey': 159,
 'S Attwell': 158,
 'P Walton': 148,
 'A Wiley': 145,
 'S Bennett': 139,
 'N Swarbrick': 132,
 'P Tierney': 128,
 'R Styles': 111,
 'C Kavanagh': 106,
 'M Riley': 102,
 'G Scott': 93,
 'R Madley': 91,
 'R East': 91,
 'D Coote': 69,
 'G Poll': 61,
 'U Rennie': 50,
 'S Hooper': 48,
 'A Madley': 45,
 'P Bankes': 39,
 'D Gallagher': 32,
 'D England': 27,
 'S Tanner': 26,
 'R Jones': 22,
 'K Stroud': 17,
 'J Gillett': 9,
 'B Knight': 5,
 'J Brooks': 4,
 'M Salisbury': 3,
 'T Harrington': 3,
 'R Beeby': 2,
 'Mn Atkinson': 2,
 'l Mason': 1,
 'O Langford': 1,
 'D Gallagh': 1,
 'T Robinson': 1,
 'S Scott': 1,
 "A D'Urso": 1,
 'A Moss': 1,
 'I Williamson': 1,
 'St Bennett': 1,
 'D Gallaghe': 1}

In [46]:
#goal diffrence
teams_goal_diff = {teams[i]: 0 for i in range(len(teams))}

for ind in df.index:
    h,a = df['HomeTeam'][ind], df['AwayTeam'][ind]
    goal_diff = df['FTHG'][ind]-df['FTAG'][ind]
    if df['FTR'][ind]=='H':
        teams_goal_diff[h]+=goal_diff
        teams_goal_diff[a]-=goal_diff
    elif df['FTR'][ind]=='A':
        teams_goal_diff[a]+=goal_diff
        teams_goal_diff[h]-=goal_diff

teams_goal_diff = dict(sorted(teams_goal_diff.items(), key = lambda x: x[1], reverse = True))
teams_goal_diff

{'Man City': 136.0,
 'Man United': 117.0,
 'Arsenal': 78.0,
 'Tottenham': 72.0,
 'Everton': 65.0,
 'Chelsea': 62.0,
 'Liverpool': 58.0,
 'Leicester': 32.0,
 'Fulham': 25.0,
 'Wolves': 17.0,
 'West Brom': 9.0,
 'Southampton': 4.0,
 'Brighton': 4.0,
 'Middlesbrough': 2.0,
 'Reading': 2.0,
 'Cardiff': 1.0,
 'Derby': -5.0,
 'Swansea': -5.0,
 'Brentford': -6.0,
 'Charlton': -8.0,
 'Crystal Palace': -10.0,
 'Bolton': -13.0,
 'Blackpool': -17.0,
 'Sheffield United': -18.0,
 'West Ham': -19.0,
 'Hull': -20.0,
 'Huddersfield': -20.0,
 'Leeds': -21.0,
 'Bournemouth': -23.0,
 'Birmingham': -28.0,
 'Blackburn': -28.0,
 'QPR': -32.0,
 'Portsmouth': -33.0,
 'Watford': -34.0,
 'Stoke': -37.0,
 'Burnley': -37.0,
 'Norwich': -45.0,
 'Sunderland': -46.0,
 'Aston Villa': -49.0,
 'Wigan': -50.0,
 'Newcastle': -80.0}

In [47]:
#number of goals scored per match 
goals_perMatch = {}
for team in teams:
    goals_perMatch[team] = round(total_goals[team]/total_matches[team],2)
goals_perMatch = dict(sorted(goals_perMatch.items(), key = lambda x: x[1], reverse = True))
goals_perMatch

{'Liverpool': 2.45,
 'Man City': 2.42,
 'Man United': 2.37,
 'Chelsea': 2.37,
 'Arsenal': 2.34,
 'Tottenham': 2.18,
 'Leicester': 1.99,
 'Blackpool': 1.9,
 'Everton': 1.88,
 'Southampton': 1.74,
 'Leeds': 1.73,
 'West Ham': 1.68,
 'Aston Villa': 1.67,
 'Bournemouth': 1.64,
 'Blackburn': 1.63,
 'Brentford': 1.55,
 'Newcastle': 1.54,
 'Bolton': 1.53,
 'Swansea': 1.53,
 'Brighton': 1.52,
 'Reading': 1.49,
 'Fulham': 1.48,
 'Crystal Palace': 1.48,
 'West Brom': 1.47,
 'Stoke': 1.47,
 'Wolves': 1.45,
 'Birmingham': 1.42,
 'Middlesbrough': 1.41,
 'Portsmouth': 1.41,
 'Wigan': 1.39,
 'Sunderland': 1.38,
 'Watford': 1.33,
 'Burnley': 1.32,
 'QPR': 1.31,
 'Charlton': 1.29,
 'Hull': 1.27,
 'Norwich': 1.2,
 'Cardiff': 1.05,
 'Sheffield United': 0.99,
 'Huddersfield': 0.85,
 'Derby': 0.67}

In [48]:
#number of goals conced per match 
goalsCon_perMatch = {}
for team in teams:
    goalsCon_perMatch[team] = round(conceded[team]/total_matches[team],2)
goalsCon_perMatch = dict(sorted(goalsCon_perMatch.items(), key = lambda x: x[1], reverse = True))
goalsCon_perMatch

{'Derby': 2.97,
 'Blackpool': 2.69,
 'Norwich': 2.37,
 'Hull': 2.27,
 'Cardiff': 2.27,
 'Huddersfield': 2.27,
 'QPR': 2.26,
 'Bournemouth': 2.24,
 'Leeds': 2.22,
 'Watford': 2.14,
 'West Brom': 2.13,
 'Wigan': 2.11,
 'Fulham': 2.07,
 'Sunderland': 2.07,
 'Birmingham': 2.07,
 'Brighton': 2.06,
 'Reading': 2.04,
 'Aston Villa': 2.03,
 'Middlesbrough': 2.0,
 'Burnley': 2.0,
 'Charlton': 1.98,
 'Newcastle': 1.98,
 'Blackburn': 1.97,
 'Southampton': 1.97,
 'Bolton': 1.96,
 'West Ham': 1.95,
 'Stoke': 1.94,
 'Wolves': 1.92,
 'Swansea': 1.92,
 'Portsmouth': 1.87,
 'Crystal Palace': 1.84,
 'Brentford': 1.81,
 'Leicester': 1.76,
 'Sheffield United': 1.71,
 'Everton': 1.7,
 'Tottenham': 1.5,
 'Arsenal': 1.39,
 'Liverpool': 1.26,
 'Man United': 1.21,
 'Man City': 1.19,
 'Chelsea': 1.17}

In [49]:
#number of red cards per match 
RCards_perMatch = {}
for team in teams:
    RCards_perMatch[team] = round(total_red[team]/total_matches[team],2)
RCards_perMatch = dict(sorted(RCards_perMatch.items(), key = lambda x: x[1], reverse = True))
RCards_perMatch

{'Blackburn': 0.17,
 'Hull': 0.17,
 'QPR': 0.17,
 'Sunderland': 0.14,
 'Birmingham': 0.13,
 'Newcastle': 0.13,
 'Brighton': 0.13,
 'Arsenal': 0.12,
 'Wigan': 0.12,
 'Charlton': 0.12,
 'Watford': 0.12,
 'Huddersfield': 0.12,
 'Everton': 0.11,
 'Bolton': 0.11,
 'Stoke': 0.11,
 'Portsmouth': 0.1,
 'Chelsea': 0.1,
 'Reading': 0.1,
 'Southampton': 0.1,
 'Brentford': 0.1,
 'Aston Villa': 0.09,
 'Man City': 0.09,
 'West Ham': 0.09,
 'West Brom': 0.09,
 'Leicester': 0.09,
 'Fulham': 0.08,
 'Middlesbrough': 0.08,
 'Tottenham': 0.08,
 'Sheffield United': 0.08,
 'Wolves': 0.08,
 'Norwich': 0.08,
 'Man United': 0.07,
 'Blackpool': 0.07,
 'Swansea': 0.07,
 'Leeds': 0.07,
 'Liverpool': 0.06,
 'Bournemouth': 0.06,
 'Crystal Palace': 0.05,
 'Burnley': 0.04,
 'Derby': 0.03,
 'Cardiff': 0.03}

In [50]:
#number of yellow cards per match 
YCards_perMatch = {}
for team in teams:
    YCards_perMatch[team] = round(total_yellow[team]/total_matches[team],2)
YCards_perMatch = dict(sorted(YCards_perMatch.items(), key = lambda x: x[1], reverse = True))
YCards_perMatch

{'Leeds': 2.68,
 'Stoke': 2.54,
 'Sunderland': 2.5,
 'Blackburn': 2.48,
 'Middlesbrough': 2.47,
 'Aston Villa': 2.42,
 'Birmingham': 2.41,
 'Bolton': 2.33,
 'Watford': 2.32,
 'Hull': 2.32,
 'Brighton': 2.29,
 'Wigan': 2.27,
 'West Brom': 2.23,
 'Burnley': 2.23,
 'Newcastle': 2.22,
 'West Ham': 2.21,
 'Sheffield United': 2.2,
 'QPR': 2.17,
 'Crystal Palace': 2.17,
 'Everton': 2.16,
 'Wolves': 2.16,
 'Man United': 2.11,
 'Norwich': 2.09,
 'Southampton': 2.09,
 'Derby': 2.07,
 'Portsmouth': 2.06,
 'Arsenal': 2.02,
 'Fulham': 2.01,
 'Tottenham': 2.01,
 'Chelsea': 2.0,
 'Bournemouth': 1.98,
 'Huddersfield': 1.97,
 'Brentford': 1.97,
 'Man City': 1.89,
 'Swansea': 1.85,
 'Leicester': 1.85,
 'Cardiff': 1.81,
 'Charlton': 1.79,
 'Liverpool': 1.75,
 'Blackpool': 1.62,
 'Reading': 1.6}

In [51]:
#number of fouls per match 
fouls_perMatch = {}
for team in teams:
    fouls_perMatch[team] = round(total_fouls[team]/total_matches[team],2)
fouls_perMatch = dict(sorted(fouls_perMatch.items(), key = lambda x: x[1], reverse = True))
fouls_perMatch

{'Middlesbrough': 17.98,
 'Blackburn': 17.58,
 'Portsmouth': 17.07,
 'Birmingham': 17.01,
 'Bolton': 16.91,
 'Derby': 16.8,
 'Brighton': 16.65,
 'Aston Villa': 16.49,
 'Stoke': 16.49,
 'Hull': 16.39,
 'Watford': 16.2,
 'Wigan': 16.18,
 'Everton': 15.99,
 'Charlton': 15.76,
 'Sunderland': 15.71,
 'Fulham': 15.43,
 'Southampton': 15.39,
 'West Brom': 15.3,
 'Crystal Palace': 14.98,
 'Leeds': 14.93,
 'Newcastle': 14.92,
 'West Ham': 14.7,
 'Sheffield United': 14.39,
 'Wolves': 14.36,
 'Man United': 14.14,
 'Blackpool': 13.9,
 'Burnley': 13.88,
 'QPR': 13.86,
 'Tottenham': 13.83,
 'Huddersfield': 13.83,
 'Leicester': 13.76,
 'Liverpool': 13.62,
 'Chelsea': 13.61,
 'Norwich': 13.42,
 'Reading': 13.37,
 'Arsenal': 13.25,
 'Swansea': 13.18,
 'Man City': 12.99,
 'Bournemouth': 12.07,
 'Brentford': 11.97,
 'Cardiff': 11.52}

In [52]:
#number of shots per match 
shots_perMatch = {}
for team in teams:
    shots_perMatch[team] = round(total_shots[team]/total_matches[team],2)
shots_perMatch = dict(sorted(shots_perMatch.items(), key = lambda x: x[1], reverse = True))
shots_perMatch

{'Liverpool': 20.88,
 'Chelsea': 19.91,
 'Man City': 18.54,
 'Tottenham': 18.54,
 'Man United': 18.44,
 'Arsenal': 18.28,
 'Southampton': 17.8,
 'Brighton': 17.49,
 'Everton': 16.95,
 'QPR': 16.95,
 'Leeds': 16.78,
 'Leicester': 16.26,
 'Portsmouth': 15.9,
 'Wigan': 15.74,
 'Aston Villa': 15.48,
 'West Ham': 15.39,
 'Blackpool': 15.38,
 'West Brom': 15.33,
 'Fulham': 15.13,
 'Newcastle': 15.07,
 'Bournemouth': 15.05,
 'Swansea': 14.82,
 'Wolves': 14.78,
 'Crystal Palace': 14.73,
 'Bolton': 14.65,
 'Middlesbrough': 14.57,
 'Sunderland': 14.56,
 'Norwich': 14.41,
 'Blackburn': 14.37,
 'Stoke': 14.32,
 'Brentford': 14.26,
 'Hull': 14.1,
 'Watford': 14.09,
 'Burnley': 13.78,
 'Birmingham': 13.36,
 'Cardiff': 13.27,
 'Huddersfield': 12.88,
 'Charlton': 12.45,
 'Reading': 11.79,
 'Sheffield United': 11.75,
 'Derby': 11.17}

In [53]:
#number of shots on target per match 
sot_perMatch = {}
for team in teams:
    sot_perMatch[team] = round(total_sot[team]/total_matches[team],2)
sot_perMatch = dict(sorted(sot_perMatch.items(), key = lambda x: x[1], reverse = True))
sot_perMatch

{'Liverpool': 9.17,
 'Chelsea': 8.82,
 'Man United': 8.7,
 'Tottenham': 8.59,
 'Arsenal': 8.5,
 'Portsmouth': 8.45,
 'Wigan': 8.18,
 'Man City': 8.1,
 'Blackpool': 8.1,
 'Bolton': 8.04,
 'Everton': 7.55,
 'Blackburn': 7.53,
 'QPR': 7.5,
 'Fulham': 7.33,
 'Middlesbrough': 7.12,
 'Birmingham': 6.97,
 'Aston Villa': 6.89,
 'Sunderland': 6.6,
 'Newcastle': 6.48,
 'West Ham': 6.46,
 'West Brom': 6.44,
 'Southampton': 6.42,
 'Wolves': 6.14,
 'Derby': 6.07,
 'Charlton': 6.05,
 'Swansea': 6.0,
 'Reading': 5.93,
 'Leeds': 5.88,
 'Leicester': 5.72,
 'Norwich': 5.57,
 'Stoke': 5.54,
 'Hull': 5.5,
 'Brighton': 5.3,
 'Bournemouth': 5.07,
 'Brentford': 4.97,
 'Burnley': 4.84,
 'Crystal Palace': 4.84,
 'Watford': 4.77,
 'Sheffield United': 4.52,
 'Cardiff': 4.0,
 'Huddersfield': 3.88}

In [54]:
#number of corners per match 
corners_perMatch = {}
for team in teams:
    corners_perMatch[team] = round(total_corners[team]/total_matches[team],2)
corners_perMatch = dict(sorted(corners_perMatch.items(), key = lambda x: x[1], reverse = True))
corners_perMatch

{'Liverpool': 8.75,
 'Man City': 8.06,
 'Chelsea': 8.06,
 'Arsenal': 8.05,
 'Tottenham': 7.8,
 'Reading': 7.77,
 'Man United': 7.75,
 'Aston Villa': 7.65,
 'Southampton': 7.59,
 'Everton': 7.54,
 'Brighton': 7.34,
 'Portsmouth': 7.21,
 'Birmingham': 7.18,
 'Wolves': 7.1,
 'Leicester': 7.0,
 'Bolton': 6.98,
 'Bournemouth': 6.9,
 'West Ham': 6.76,
 'Blackburn': 6.73,
 'Middlesbrough': 6.72,
 'West Brom': 6.72,
 'Leeds': 6.7,
 'Wigan': 6.61,
 'Crystal Palace': 6.56,
 'Fulham': 6.48,
 'Blackpool': 6.41,
 'Swansea': 6.4,
 'Sunderland': 6.34,
 'Newcastle': 6.34,
 'Stoke': 6.32,
 'QPR': 6.18,
 'Sheffield United': 6.12,
 'Norwich': 6.05,
 'Watford': 5.98,
 'Hull': 5.96,
 'Burnley': 5.85,
 'Cardiff': 5.78,
 'Charlton': 5.57,
 'Huddersfield': 5.54,
 'Derby': 5.2,
 'Brentford': 5.13}

In [55]:
# wins per match 
win_perMatch = {}
for team in teams:
    win_perMatch[team] = round(total_team_wins[team]/total_matches[team],2)
win_perMatch = dict(sorted(win_perMatch.items(), key = lambda x: x[1], reverse = True))
win_perMatch

{'Man United': 0.77,
 'Chelsea': 0.76,
 'Liverpool': 0.75,
 'Man City': 0.72,
 'Arsenal': 0.7,
 'Tottenham': 0.65,
 'Everton': 0.55,
 'Leicester': 0.53,
 'Blackburn': 0.45,
 'Southampton': 0.45,
 'Leeds': 0.45,
 'West Ham': 0.44,
 'Stoke': 0.43,
 'Aston Villa': 0.42,
 'Newcastle': 0.42,
 'Brentford': 0.42,
 'Bolton': 0.41,
 'Wolves': 0.41,
 'Swansea': 0.41,
 'Crystal Palace': 0.41,
 'Portsmouth': 0.4,
 'Bournemouth': 0.38,
 'Brighton': 0.38,
 'Fulham': 0.37,
 'Wigan': 0.37,
 'Charlton': 0.36,
 'Burnley': 0.36,
 'Birmingham': 0.35,
 'West Brom': 0.35,
 'Reading': 0.35,
 'Middlesbrough': 0.34,
 'Sheffield United': 0.34,
 'Blackpool': 0.34,
 'Watford': 0.33,
 'Sunderland': 0.32,
 'Hull': 0.29,
 'Norwich': 0.28,
 'Cardiff': 0.27,
 'QPR': 0.25,
 'Huddersfield': 0.2,
 'Derby': 0.03}

In [56]:
# loss per match 
loss_perMatch = {}
for team in teams:
    loss_perMatch[team] = round(total_team_loss[team]/total_matches[team],2)
loss_perMatch = dict(sorted(loss_perMatch.items(), key = lambda x: x[1], reverse = True))
loss_perMatch

{'Derby': 0.97,
 'Huddersfield': 0.8,
 'QPR': 0.75,
 'Cardiff': 0.73,
 'Norwich': 0.72,
 'Hull': 0.71,
 'Sunderland': 0.68,
 'Watford': 0.67,
 'Middlesbrough': 0.66,
 'Sheffield United': 0.66,
 'Blackpool': 0.66,
 'Birmingham': 0.65,
 'West Brom': 0.65,
 'Reading': 0.65,
 'Charlton': 0.64,
 'Burnley': 0.64,
 'Fulham': 0.63,
 'Wigan': 0.63,
 'Bournemouth': 0.62,
 'Brighton': 0.62,
 'Portsmouth': 0.6,
 'Bolton': 0.59,
 'Swansea': 0.59,
 'Crystal Palace': 0.59,
 'Aston Villa': 0.58,
 'Newcastle': 0.58,
 'Wolves': 0.58,
 'Brentford': 0.58,
 'Stoke': 0.57,
 'West Ham': 0.56,
 'Blackburn': 0.55,
 'Southampton': 0.55,
 'Leeds': 0.55,
 'Leicester': 0.47,
 'Everton': 0.45,
 'Tottenham': 0.35,
 'Arsenal': 0.3,
 'Man City': 0.28,
 'Liverpool': 0.25,
 'Chelsea': 0.24,
 'Man United': 0.23}

In [57]:
# draws per match 
draws_perMatch = {}
for team in teams:
    draws_perMatch[team] = round(totalTeam_draws[team]/total_matches[team],2)
draws_perMatch = dict(sorted(draws_perMatch.items(), key = lambda x: x[1], reverse = True))
draws_perMatch

{'Brighton': 0.52,
 'Birmingham': 0.45,
 'Middlesbrough': 0.41,
 'Stoke': 0.4,
 'Aston Villa': 0.39,
 'Everton': 0.39,
 'West Brom': 0.38,
 'Southampton': 0.38,
 'Fulham': 0.37,
 'Sunderland': 0.36,
 'Hull': 0.34,
 'Portsmouth': 0.33,
 'Wigan': 0.33,
 'Wolves': 0.33,
 'Burnley': 0.33,
 'Swansea': 0.33,
 'West Ham': 0.32,
 'Blackburn': 0.32,
 'Newcastle': 0.32,
 'Charlton': 0.31,
 'Liverpool': 0.31,
 'Blackpool': 0.31,
 'Norwich': 0.31,
 'Crystal Palace': 0.31,
 'Tottenham': 0.3,
 'Bolton': 0.3,
 'QPR': 0.3,
 'Leicester': 0.3,
 'Arsenal': 0.29,
 'Watford': 0.29,
 'Bournemouth': 0.29,
 'Huddersfield': 0.29,
 'Chelsea': 0.28,
 'Man United': 0.27,
 'Derby': 0.27,
 'Leeds': 0.27,
 'Reading': 0.25,
 'Sheffield United': 0.24,
 'Brentford': 0.23,
 'Man City': 0.21,
 'Cardiff': 0.21}

In [58]:
# Team performance by season
for season in seasons:
    print(f"season: 20{season[1:3]}-20{season[3:]}")
    for team in teams:
        ht_data = df[(df['HomeTeam']==team) & (df['Div']==season)]
        at_data = df[(df['AwayTeam']==team) & (df['Div']==season)]
        matches_played = ht_data.shape[0]+at_data.shape[0]
        if matches_played==0:
            break
        print("\tTeam name:",team)
        
        home_team_wins = ht_data[ht_data['FTR']=='H'].shape[0]
        away_team_wins = at_data[at_data['FTR']=='A'].shape[0]
        total_team_wins = home_team_wins + away_team_wins
        
        home_team_loss = ht_data[ht_data['FTR']=='A'].shape[0]
        away_team_loss = at_data[at_data['FTR']=='H'].shape[0]
        total_team_loss = home_team_loss + away_team_loss
        
        h_draws = ht_data[ht_data['FTR']=='D'].shape[0]
        a_draws = at_data[at_data['FTR']=='D'].shape[0]
        total_draws = h_draws + a_draws
        
        h_goals = ht_data['FTHG'].sum()
        a_goals = at_data['FTAG'].sum()
        total_goals = h_goals + a_goals
        
        h_conced = ht_data['FTAG'].sum()
        a_conced = at_data['FTAG'].sum()
        total_conced = h_conced + a_conced
        
        h_shots = ht_data['HS'].sum()
        a_shots = at_data['AS'].sum()
        total_shots = h_shots + a_shots
        
        h_sot = ht_data['HST'].sum()
        a_sot = at_data['AST'].sum()
        total_sot = h_sot + a_sot
        
        h_foul = ht_data['HF'].sum()
        a_foul = at_data['AF'].sum()
        total_fouls = h_foul + a_foul
        
        h_corner = ht_data['HC'].sum()
        a_corner = at_data['AC'].sum()
        total_corner = h_corner + a_corner
        
        h_yellow = ht_data['HY'].sum()
        a_yellow = at_data['AY'].sum()
        total_yellow = h_yellow + a_yellow
        
        h_red = ht_data['HR'].sum()
        a_red = at_data['AR'].sum()
        total_red = h_red + a_red
        
#         df = pd.concat([ht_data, at_data])
#         teams_goal_diff = {team:0}
#         for ind in df.index:
#             h,a = df['HomeTeam'][ind], df['AwayTeam'][ind]
#             goal_diff = df['FTHG'][ind]-df['FTAG'][ind]
#             if df['FTR'][ind]=='H':
#                 teams_goal_diff[h]+=goal_diff
#             elif df['FTR'][ind]=='A':
#                 teams_goal_diff[a]+=goal_diff
#                 teams_goal_diff[h]-=goal_diff
        
        print("\t\tMatches played:",matches_played,'\n',
              "\t\tWon:",total_team_wins,'\n',
              "\t\tLost:",total_team_loss,'\n',
              "\t\tDraw:",total_draws,'\n',
              "\t\tgoals_scored:",total_goals,'\n',
              "\t\tgoals_conceded:",total_conced,'\n',
              "\t\ttotal_fouls:",total_fouls,'\n',
              "\t\ttotal_shots:",total_shots,'\n',
              "\t\ttotal_sot:",total_sot,'\n',
              "\t\ttotal_corner:",total_corner,'\n',
              "\t\ttotal_yellow cards:",total_yellow,'\n',
              "\t\ttotal_red cards:",total_red,'\n')
              #"\t\tGoal diff:",teams_goal_diff)
        #break
    break

season: 2005-2006
	Team name: Aston Villa
		Matches played: 38
 		Won: 10
 		Lost: 16
 		Draw: 12
 		goals_scored: 42.0
 		goals_conceded: 42.0
 		total_fouls: 537.0
 		total_shots: 378.0
 		total_sot: 197.0
 		total_corner: 237.0
 		total_yellow cards: 62.0
 		total_red cards: 2.0

	Team name: Everton
		Matches played: 38
 		Won: 14
 		Lost: 16
 		Draw: 8
 		goals_scored: 34.0
 		goals_conceded: 34.0
 		total_fouls: 535.0
 		total_shots: 378.0
 		total_sot: 206.0
 		total_corner: 236.0
 		total_yellow cards: 65.0
 		total_red cards: 7.0

	Team name: Fulham
		Matches played: 38
 		Won: 14
 		Lost: 18
 		Draw: 6
 		goals_scored: 48.0
 		goals_conceded: 38.0
 		total_fouls: 460.0
 		total_shots: 358.0
 		total_sot: 178.0
 		total_corner: 165.0
 		total_yellow cards: 63.0
 		total_red cards: 2.0

	Team name: Man City
		Matches played: 38
 		Won: 13
 		Lost: 21
 		Draw: 4
 		goals_scored: 43.0
 		goals_conceded: 37.0
 		total_fouls: 514.0
 		total_shots: 430.0
 		total_sot: 212.0
 		total_corner: 203.0
 		total_yellow cards: 70.0
 		total_red cards: 4.0

	Team name: Middlesbrough
		Matches played: 38
 		Won: 12
 		Lost: 17
 		Draw: 9
 		goals_scored: 48.0
 		goals_conceded: 50.0
 		total_fouls: 496.0
 		total_shots: 396.0
 		total_sot: 219.0
 		total_corner: 184.0
 		total_yellow cards: 54.0
 		total_red cards: 3.0

	Team name: Portsmouth
		Matches played: 38
 		Won: 10
 		Lost: 20
 		Draw: 8
 		goals_scored: 37.0
 		goals_conceded: 44.0
 		total_fouls: 496.0
 		total_shots: 411.0
 		total_sot: 222.0
 		total_corner: 218.0
 		total_yellow cards: 54.0
 		total_red cards: 1.0

	Team name: Sunderland
		Matches played: 38
 		Won: 3
 		Lost: 29
 		Draw: 6
 		goals_scored: 26.0
 		goals_conceded: 51.0
 		total_fouls: 538.0
 		total_shots: 337.0
 		total_sot: 183.0
 		total_corner: 177.0
 		total_yellow cards: 69.0
 		total_red cards: 4.0

	Team name: West Ham
		Matches played: 38
 		Won: 16
 		Lost: 15
 		Draw: 7
 		goals_scored: 52.0
 		goals_conceded: 47.0
 		total_fouls: 497.0
 		total_shots: 354.0
 		total_sot: 173.0
 		total_corner: 206.0
 		total_yellow cards: 50.0
 		total_red cards: 2.0

	Team name: Arsenal
		Matches played: 38
 		Won: 20
 		Lost: 11
 		Draw: 7
 		goals_scored: 68.0
 		goals_conceded: 33.0
 		total_fouls: 479.0
 		total_shots: 462.0
 		total_sot: 274.0
 		total_corner: 211.0
 		total_yellow cards: 55.0
 		total_red cards: 2.0

	Team name: Wigan
		Matches played: 38
 		Won: 15
 		Lost: 17
 		Draw: 6
 		goals_scored: 45.0
 		goals_conceded: 47.0
 		total_fouls: 493.0
 		total_shots: 433.0
 		total_sot: 207.0
 		total_corner: 169.0
 		total_yellow cards: 54.0
 		total_red cards: 4.0

	Team name: Birmingham
		Matches played: 38
 		Won: 8
 		Lost: 20
 		Draw: 10
 		goals_scored: 28.0
 		goals_conceded: 29.0
 		total_fouls: 483.0
 		total_shots: 354.0
 		total_sot: 168.0
 		total_corner: 218.0
 		total_yellow cards: 53.0
 		total_red cards: 7.0

	Team name: Blackburn
		Matches played: 38
 		Won: 19
 		Lost: 13
 		Draw: 6
 		goals_scored: 51.0
 		goals_conceded: 37.0
 		total_fouls: 568.0
 		total_shots: 384.0
 		total_sot: 183.0
 		total_corner: 230.0
 		total_yellow cards: 76.0
 		total_red cards: 6.0

	Team name: Charlton
		Matches played: 38
 		Won: 13
 		Lost: 17
 		Draw: 8
 		goals_scored: 41.0
 		goals_conceded: 40.0
 		total_fouls: 486.0
 		total_shots: 371.0
 		total_sot: 183.0
 		total_corner: 143.0
 		total_yellow cards: 46.0
 		total_red cards: 3.0

	Team name: Liverpool
		Matches played: 38
 		Won: 25
 		Lost: 6
 		Draw: 7
 		goals_scored: 57.0
 		goals_conceded: 33.0
 		total_fouls: 438.0
 		total_shots: 563.0
 		total_sot: 283.0
 		total_corner: 234.0
 		total_yellow cards: 50.0
 		total_red cards: 5.0

	Team name: Man United
		Matches played: 38
 		Won: 25
 		Lost: 5
 		Draw: 8
 		goals_scored: 72.0
 		goals_conceded: 43.0
 		total_fouls: 486.0
 		total_shots: 555.0
 		total_sot: 286.0
 		total_corner: 221.0
 		total_yellow cards: 60.0
 		total_red cards: 2.0

	Team name: Newcastle
		Matches played: 38
 		Won: 17
 		Lost: 14
 		Draw: 7
 		goals_scored: 47.0
 		goals_conceded: 34.0
 		total_fouls: 600.0
 		total_shots: 370.0
 		total_sot: 208.0
 		total_corner: 190.0
 		total_yellow cards: 66.0
 		total_red cards: 7.0

	Team name: Tottenham
		Matches played: 38
 		Won: 18
 		Lost: 9
 		Draw: 11
 		goals_scored: 53.0
 		goals_conceded: 38.0
 		total_fouls: 466.0
 		total_shots: 411.0
 		total_sot: 234.0
 		total_corner: 210.0
 		total_yellow cards: 52.0
 		total_red cards: 5.0

	Team name: West Brom
		Matches played: 38
 		Won: 7
 		Lost: 22
 		Draw: 9
 		goals_scored: 31.0
 		goals_conceded: 34.0
 		total_fouls: 487.0
 		total_shots: 332.0
 		total_sot: 163.0
 		total_corner: 177.0
 		total_yellow cards: 47.0
 		total_red cards: 2.0

	Team name: Bolton
		Matches played: 38
 		Won: 15
 		Lost: 12
 		Draw: 11
 		goals_scored: 49.0
 		goals_conceded: 33.0
 		total_fouls: 505.0
 		total_shots: 402.0
 		total_sot: 198.0
 		total_corner: 198.0
 		total_yellow cards: 64.0
 		total_red cards: 3.0

	Team name: Chelsea
		Matches played: 38
 		Won: 29
 		Lost: 5
 		Draw: 4
 		goals_scored: 72.0
 		goals_conceded: 34.0
 		total_fouls: 434.0
 		total_shots: 514.0
 		total_sot: 277.0
 		total_corner: 224.0
 		total_yellow cards: 63.0
 		total_red cards: 5.0

In [59]:
#Seasonal performance of team
for team in teams:
    print("Team name:",team)
    for season in seasons:
        ht_data = df[(df['HomeTeam']==team) & (df['Div']==season)]
        at_data = df[(df['AwayTeam']==team) & (df['Div']==season)]
        matches_played = ht_data.shape[0]+at_data.shape[0]
        print(f"\tseason: 20{season[1:3]}-20{season[3:]}")
        
        home_team_wins = ht_data[ht_data['FTR']=='H'].shape[0]
        away_team_wins = at_data[at_data['FTR']=='A'].shape[0]
        total_team_wins = home_team_wins + away_team_wins
        
        home_team_loss = ht_data[ht_data['FTR']=='A'].shape[0]
        away_team_loss = at_data[at_data['FTR']=='H'].shape[0]
        total_team_loss = home_team_loss + away_team_loss
        
        h_draws = ht_data[ht_data['FTR']=='D'].shape[0]
        a_draws = at_data[at_data['FTR']=='D'].shape[0]
        total_draws = h_draws + a_draws
        
        h_goals = ht_data['FTHG'].sum()
        a_goals = at_data['FTAG'].sum()
        total_goals = h_goals + a_goals
        
        h_conced = ht_data['FTAG'].sum()
        a_conced = at_data['FTAG'].sum()
        total_conced = h_conced + a_conced
        
        h_shots = ht_data['HS'].sum()
        a_shots = at_data['AS'].sum()
        total_shots = h_shots + a_shots
        
        h_sot = ht_data['HST'].sum()
        a_sot = at_data['AST'].sum()
        total_sot = h_sot + a_sot
        
        h_foul = ht_data['HF'].sum()
        a_foul = at_data['AF'].sum()
        total_fouls = h_foul + a_foul
        
        h_corner = ht_data['HC'].sum()
        a_corner = at_data['AC'].sum()
        total_corner = h_corner + a_corner
        
        h_yellow = ht_data['HY'].sum()
        a_yellow = at_data['AY'].sum()
        total_yellow = h_yellow + a_yellow
        
        h_red = ht_data['HR'].sum()
        a_red = at_data['AR'].sum()
        total_red = h_red + a_red
        
#         df = pd.concat([ht_data, at_data])
#         teams_goal_diff = {team:0}
#         for ind in df.index:
#             h,a = df['HomeTeam'][ind], df['AwayTeam'][ind]
#             goal_diff = df['FTHG'][ind]-df['FTAG'][ind]
#             if df['FTR'][ind]=='H':
#                 teams_goal_diff[h]+=goal_diff
#             elif df['FTR'][ind]=='A':
#                 teams_goal_diff[a]+=goal_diff
#                 teams_goal_diff[h]-=goal_diff
        
        print("\t\tMatches played:",matches_played,'\n',
              "\t\tWon:",total_team_wins,'\n',
              "\t\tLost:",total_team_loss,'\n',
              "\t\tDraw:",total_draws,'\n',
              "\t\tgoals_scored:",total_goals,'\n',
              "\t\tgoals_conceded:",total_conced,'\n',
              "\t\ttotal_fouls:",total_fouls,'\n',
              "\t\ttotal_shots:",total_shots,'\n',
              "\t\ttotal_sot:",total_sot,'\n',
              "\t\ttotal_corner:",total_corner,'\n',
              "\t\ttotal_yellow cards:",total_yellow,'\n',
              "\t\ttotal_red cards:",total_red,'\n')
              #"\t\tGoal diff:",teams_goal_diff)
        #break
    break

Team name: Aston Villa
	season: 2005-2006
		Matches played: 38
 		Won: 10
 		Lost: 16
 		Draw: 12
 		goals_scored: 42.0
 		goals_conceded: 42.0
 		total_fouls: 537.0
 		total_shots: 378.0
 		total_sot: 197.0
 		total_corner: 237.0
 		total_yellow cards: 62.0
 		total_red cards: 2.0

	season: 2006-2007
		Matches played: 38
 		Won: 11
 		Lost: 10
 		Draw: 17
 		goals_scored: 43.0
 		goals_conceded: 37.0
 		total_fouls: 500.0
 		total_shots: 404.0
 		total_sot: 211.0
 		total_corner: 213.0
 		total_yellow cards: 48.0
 		total_red cards: 1.0

	season: 2007-2008
		Matches played: 38
 		Won: 16
 		Lost: 10
 		Draw: 12
 		goals_scored: 71.0
 		goals_conceded: 59.0
 		total_fouls: 508.0
 		total_shots: 414.0
 		total_sot: 221.0
 		total_corner: 228.0
 		total_yellow cards: 56.0
 		total_red cards: 4.0

	season: 2008-2009
		Matches played: 38
 		Won: 17
 		Lost: 10
 		Draw: 11
 		goals_scored: 54.0
 		goals_conceded: 48.0
 		total_fouls: 431.0
 		total_shots: 408.0
 		total_sot: 225.0
 		total_corner: 260.0
 		total_yellow cards: 53.0
 		total_red cards: 2.0

	season: 2009-2010
		Matches played: 38
 		Won: 17
 		Lost: 8
 		Draw: 13
 		goals_scored: 52.0
 		goals_conceded: 39.0
 		total_fouls: 460.0
 		total_shots: 429.0
 		total_sot: 239.0
 		total_corner: 241.0
 		total_yellow cards: 61.0
 		total_red cards: 2.0

	season: 2010-2011
		Matches played: 38
 		Won: 12
 		Lost: 14
 		Draw: 12
 		goals_scored: 48.0
 		goals_conceded: 41.0
 		total_fouls: 437.0
 		total_shots: 436.0
 		total_sot: 241.0
 		total_corner: 235.0
 		total_yellow cards: 71.0
 		total_red cards: 2.0

	season: 2011-2012
		Matches played: 38
 		Won: 7
 		Lost: 14
 		Draw: 17
 		goals_scored: 37.0
 		goals_conceded: 42.0
 		total_fouls: 393.0
 		total_shots: 404.0
 		total_sot: 203.0
 		total_corner: 218.0
 		total_yellow cards: 70.0
 		total_red cards: 2.0

	season: 2012-2013
		Matches played: 38
 		Won: 10
 		Lost: 17
 		Draw: 11
 		goals_scored: 47.0
 		goals_conceded: 52.0
 		total_fouls: 428.0
 		total_shots: 393.0
 		total_sot: 225.0
 		total_corner: 178.0
 		total_yellow cards: 74.0
 		total_red cards: 3.0

	season: 2013-2014
		Matches played: 38
 		Won: 10
 		Lost: 20
 		Draw: 8
 		goals_scored: 39.0
 		goals_conceded: 46.0
 		total_fouls: 484.0
 		total_shots: 430.0
 		total_sot: 134.0
 		total_corner: 163.0
 		total_yellow cards: 78.0
 		total_red cards: 0.0

	season: 2014-2015
		Matches played: 38
 		Won: 10
 		Lost: 20
 		Draw: 8
 		goals_scored: 31.0
 		goals_conceded: 38.0
 		total_fouls: 400.0
 		total_shots: 414.0
 		total_sot: 127.0
 		total_corner: 171.0
 		total_yellow cards: 70.0
 		total_red cards: 7.0

	season: 2015-2016
		Matches played: 38
 		Won: 3
 		Lost: 27
 		Draw: 8
 		goals_scored: 27.0
 		goals_conceded: 48.0
 		total_fouls: 431.0
 		total_shots: 378.0
 		total_sot: 111.0
 		total_corner: 167.0
 		total_yellow cards: 75.0
 		total_red cards: 3.0

	season: 2016-2017
		Matches played: 0
 		Won: 0
 		Lost: 0
 		Draw: 0
 		goals_scored: 0.0
 		goals_conceded: 0.0
 		total_fouls: 0.0
 		total_shots: 0.0
 		total_sot: 0.0
 		total_corner: 0.0
 		total_yellow cards: 0.0
 		total_red cards: 0.0

	season: 2017-2018
		Matches played: 0
 		Won: 0
 		Lost: 0
 		Draw: 0
 		goals_scored: 0.0
 		goals_conceded: 0.0
 		total_fouls: 0.0
 		total_shots: 0.0
 		total_sot: 0.0
 		total_corner: 0.0
 		total_yellow cards: 0.0
 		total_red cards: 0.0

	season: 2018-2019
		Matches played: 0
 		Won: 0
 		Lost: 0
 		Draw: 0
 		goals_scored: 0.0
 		goals_conceded: 0.0
 		total_fouls: 0.0
 		total_shots: 0.0
 		total_sot: 0.0
 		total_corner: 0.0
 		total_yellow cards: 0.0
 		total_red cards: 0.0

	season: 2019-2020
		Matches played: 38
 		Won: 9
 		Lost: 21
 		Draw: 8
 		goals_scored: 41.0
 		goals_conceded: 49.0
 		total_fouls: 451.0
 		total_shots: 459.0
 		total_sot: 150.0
 		total_corner: 200.0
 		total_yellow cards: 68.0
 		total_red cards: 1.0

	season: 2020-2021
		Matches played: 38
 		Won: 16
 		Lost: 15
 		Draw: 7
 		goals_scored: 55.0
 		goals_conceded: 53.0
 		total_fouls: 439.0
 		total_shots: 511.0
 		total_sot: 187.0
 		total_corner: 215.0
 		total_yellow cards: 63.0
 		total_red cards: 3.0

	season: 2021-2022
		Matches played: 38
 		Won: 13
 		Lost: 19
 		Draw: 6
 		goals_scored: 52.0
 		goals_conceded: 52.0
 		total_fouls: 401.0
 		total_shots: 454.0
 		total_sot: 162.0
 		total_corner: 196.0
 		total_yellow cards: 77.0
 		total_red cards: 2.0

In [60]:
# a teams home vs away

for team in teams:
    print("Team name:",team)
    ht_data = df[(df['HomeTeam']==team)]
    at_data = df[(df['AwayTeam']==team)]
    
    homematches_played, awaymatches_played = ht_data.shape[0],at_data.shape[0]
    
    home_team_wins = ht_data[ht_data['FTR']=='H'].shape[0]
    away_team_wins = at_data[at_data['FTR']=='A'].shape[0]
        
    home_team_loss = ht_data[ht_data['FTR']=='A'].shape[0]
    away_team_loss = at_data[at_data['FTR']=='H'].shape[0]
        
    h_draws = ht_data[ht_data['FTR']=='D'].shape[0]
    a_draws = at_data[at_data['FTR']=='D'].shape[0]
        
    h_goals = ht_data['FTHG'].sum()
    a_goals = at_data['FTAG'].sum()
    
    h_conced = ht_data['FTAG'].sum()
    a_conced = at_data['FTAG'].sum()
    
    h_shots = ht_data['HS'].sum()
    a_shots = at_data['AS'].sum()
    
    h_sot = ht_data['HST'].sum()
    a_sot = at_data['AST'].sum()
    
    h_foul = ht_data['HF'].sum()
    a_foul = at_data['AF'].sum()
    
    h_corner = ht_data['HC'].sum()
    a_corner = at_data['AC'].sum()
    
    h_yellow = ht_data['HY'].sum()
    a_yellow = at_data['AY'].sum()
    
    h_red = ht_data['HR'].sum()
    a_red = at_data['AR'].sum()
    
    print("\t                Home - Away")
    print(f"\tMatches played  {homematches_played}    - {awaymatches_played}")
    print(f"\tWon             {home_team_wins}     - {away_team_wins}")
    print(f"\tLost            {home_team_loss}     - {away_team_loss}")
    print(f"\tDraws           {h_draws}     - {a_draws}")
    print(f"\tGoals scored    {h_goals}  - {a_goals}")
    print(f"\tGoals conceded  {h_conced}  - {a_conced}")
    print(f"\tShots           {h_shots} - {a_shots}")
    print(f"\tShots on target {h_sot} - {a_sot}")
    print(f"\tFouls           {h_foul} - {a_foul}")
    print(f"\tCorners         {h_corner} - {a_corner}")
    print(f"\tYellow card     {h_yellow}  - {a_yellow}")
    print(f"\tRed card        {h_red}   - {a_red}")
    break

Team name: Aston Villa
	                Home - Away
	Matches played  266    - 266
	Won             88     - 73
	Lost            99     - 122
	Draws           79     - 71
	Goals scored    333.0  - 306.0
	Goals conceded  340.0  - 306.0
	Shots           3216.0 - 2696.0
	Shots on target 1391.0 - 1242.0
	Fouls           3062.0 - 3238.0
	Corners         1608.0 - 1314.0
	Yellow card     401.0  - 525.0
	Red card        18.0   - 16.0

In [61]:
for team in teams:
    print("Team name:",team)
    for season in seasons:
        print(f"\t season: 20{season[1:3]}-20{season[3:]}")
        ht_data = df[(df['HomeTeam']==team) & (df['Div']==season)]
        at_data = df[(df['AwayTeam']==team) & (df['Div']==season)]
        
        homematches_played, awaymatches_played = ht_data.shape[0],at_data.shape[0]
    
        home_team_wins = ht_data[ht_data['FTR']=='H'].shape[0]
        away_team_wins = at_data[at_data['FTR']=='A'].shape[0]

        home_team_loss = ht_data[ht_data['FTR']=='A'].shape[0]
        away_team_loss = at_data[at_data['FTR']=='H'].shape[0]

        h_draws = ht_data[ht_data['FTR']=='D'].shape[0]
        a_draws = at_data[at_data['FTR']=='D'].shape[0]

        h_goals = ht_data['FTHG'].sum()
        a_goals = at_data['FTAG'].sum()

        h_conced = ht_data['FTAG'].sum()
        a_conced = at_data['FTAG'].sum()

        h_shots = ht_data['HS'].sum()
        a_shots = at_data['AS'].sum()

        h_sot = ht_data['HST'].sum()
        a_sot = at_data['AST'].sum()

        h_foul = ht_data['HF'].sum()
        a_foul = at_data['AF'].sum()

        h_corner = ht_data['HC'].sum()
        a_corner = at_data['AC'].sum()

        h_yellow = ht_data['HY'].sum()
        a_yellow = at_data['AY'].sum()

        h_red = ht_data['HR'].sum()
        a_red = at_data['AR'].sum()

        print("\t\t                Home  - Away")
        print(f"\t\tMatches played  {homematches_played}    - {awaymatches_played}")
        print(f"\t\tWon             {home_team_wins}     - {away_team_wins}")
        print(f"\t\tLost            {home_team_loss}     - {away_team_loss}")
        print(f"\t\tDraws           {h_draws}     - {a_draws}")
        print(f"\tGoals scored      {h_goals}  - {a_goals}")
        print(f"\t\tGoals conceded  {h_conced}  - {a_conced}")
        print(f"\t\tShots           {h_shots} - {a_shots}")
        print(f"\t\tShots on target {h_sot} - {a_sot}")
        print(f"\t\tFouls           {h_foul} - {a_foul}")
        print(f"\t\tCorners         {h_corner} - {a_corner}")
        print(f"\t\tYellow card     {h_yellow}  - {a_yellow}")
        print(f"\t\tRed card        {h_red}   - {a_red}")
        #break
    break

Team name: Aston Villa
	 season: 2005-2006
		                Home  - Away
		Matches played  19    - 19
		Won             6     - 4
		Lost            7     - 9
		Draws           6     - 6
	Goals scored      20.0  - 22.0
		Goals conceded  20.0  - 22.0
		Shots           212.0 - 166.0
		Shots on target 108.0 - 89.0
		Fouls           275.0 - 262.0
		Corners         125.0 - 112.0
		Yellow card     30.0  - 32.0
		Red card        0.0   - 2.0
	 season: 2006-2007
		                Home  - Away
		Matches played  19    - 19
		Won             7     - 4
		Lost            4     - 6
		Draws           8     - 9
	Goals scored      20.0  - 23.0
		Goals conceded  14.0  - 23.0
		Shots           222.0 - 182.0
		Shots on target 109.0 - 102.0
		Fouls           241.0 - 259.0
		Corners         117.0 - 96.0
		Yellow card     22.0  - 26.0
		Red card        0.0   - 1.0
	 season: 2007-2008
		                Home  - Away
		Matches played  19    - 19
		Won             10     - 6
		Lost            6     - 4
		Draws           3     - 9
	Goals scored      34.0  - 37.0
		Goals conceded  22.0  - 37.0
		Shots           215.0 - 199.0
		Shots on target 101.0 - 120.0
		Fouls           254.0 - 254.0
		Corners         117.0 - 111.0
		Yellow card     26.0  - 30.0
		Red card        2.0   - 2.0
	 season: 2008-2009
		                Home  - Away
		Matches played  19    - 19
		Won             7     - 10
		Lost            3     - 7
		Draws           9     - 2
	Goals scored      27.0  - 27.0
		Goals conceded  21.0  - 27.0
		Shots           244.0 - 164.0
		Shots on target 132.0 - 93.0
		Fouls           191.0 - 240.0
		Corners         148.0 - 112.0
		Yellow card     16.0  - 37.0
		Red card        0.0   - 2.0
	 season: 2009-2010
		                Home  - Away
		Matches played  19    - 19
		Won             8     - 9
		Lost            3     - 5
		Draws           8     - 5
	Goals scored      29.0  - 23.0
		Goals conceded  16.0  - 23.0
		Shots           226.0 - 203.0
		Shots on target 121.0 - 118.0
		Fouls           223.0 - 237.0
		Corners         138.0 - 103.0
		Yellow card     23.0  - 38.0
		Red card        0.0   - 2.0
	 season: 2010-2011
		                Home  - Away
		Matches played  19    - 19
		Won             8     - 4
		Lost            4     - 10
		Draws           7     - 5
	Goals scored      26.0  - 22.0
		Goals conceded  19.0  - 22.0
		Shots           231.0 - 205.0
		Shots on target 125.0 - 116.0
		Fouls           211.0 - 226.0
		Corners         125.0 - 110.0
		Yellow card     35.0  - 36.0
		Red card        1.0   - 1.0
	 season: 2011-2012
		                Home  - Away
		Matches played  19    - 19
		Won             4     - 3
		Lost            8     - 6
		Draws           7     - 10
	Goals scored      20.0  - 17.0
		Goals conceded  25.0  - 17.0
		Shots           225.0 - 179.0
		Shots on target 108.0 - 95.0
		Fouls           187.0 - 206.0
		Corners         129.0 - 89.0
		Yellow card     25.0  - 45.0
		Red card        2.0   - 0.0
	 season: 2012-2013
		                Home  - Away
		Matches played  19    - 19
		Won             5     - 5
		Lost            9     - 8
		Draws           5     - 6
	Goals scored      23.0  - 24.0
		Goals conceded  28.0  - 24.0
		Shots           217.0 - 176.0
		Shots on target 124.0 - 101.0
		Fouls           208.0 - 220.0
		Corners         111.0 - 67.0
		Yellow card     32.0  - 42.0
		Red card        3.0   - 0.0
	 season: 2013-2014
		                Home  - Away
		Matches played  19    - 19
		Won             6     - 4
		Lost            10     - 10
		Draws           3     - 5
	Goals scored      22.0  - 17.0
		Goals conceded  29.0  - 17.0
		Shots           233.0 - 197.0
		Shots on target 75.0 - 59.0
		Fouls           234.0 - 250.0
		Corners         94.0 - 69.0
		Yellow card     35.0  - 43.0
		Red card        0.0   - 0.0
	 season: 2014-2015
		                Home  - Away
		Matches played  19    - 19
		Won             5     - 5
		Lost            8     - 12
		Draws           6     - 2
	Goals scored      18.0  - 13.0
		Goals conceded  25.0  - 13.0
		Shots           222.0 - 192.0
		Shots on target 65.0 - 62.0
		Fouls           191.0 - 209.0
		Corners         89.0 - 82.0
		Yellow card     28.0  - 42.0
		Red card        4.0   - 3.0
	 season: 2015-2016
		                Home  - Away
		Matches played  19    - 19
		Won             2     - 1
		Lost            12     - 15
		Draws           5     - 3
	Goals scored      14.0  - 13.0
		Goals conceded  35.0  - 13.0
		Shots           216.0 - 162.0
		Shots on target 62.0 - 49.0
		Fouls           194.0 - 237.0
		Corners         94.0 - 73.0
		Yellow card     35.0  - 40.0
		Red card        1.0   - 2.0
	 season: 2016-2017
		                Home  - Away
		Matches played  0    - 0
		Won             0     - 0
		Lost            0     - 0
		Draws           0     - 0
	Goals scored      0.0  - 0.0
		Goals conceded  0.0  - 0.0
		Shots           0.0 - 0.0
		Shots on target 0.0 - 0.0
		Fouls           0.0 - 0.0
		Corners         0.0 - 0.0
		Yellow card     0.0  - 0.0
		Red card        0.0   - 0.0
	 season: 2017-2018
		                Home  - Away
		Matches played  0    - 0
		Won             0     - 0
		Lost            0     - 0
		Draws           0     - 0
	Goals scored      0.0  - 0.0
		Goals conceded  0.0  - 0.0
		Shots           0.0 - 0.0
		Shots on target 0.0 - 0.0
		Fouls           0.0 - 0.0
		Corners         0.0 - 0.0
		Yellow card     0.0  - 0.0
		Red card        0.0   - 0.0
	 season: 2018-2019
		                Home  - Away
		Matches played  0    - 0
		Won             0     - 0
		Lost            0     - 0
		Draws           0     - 0
	Goals scored      0.0  - 0.0
		Goals conceded  0.0  - 0.0
		Shots           0.0 - 0.0
		Shots on target 0.0 - 0.0
		Fouls           0.0 - 0.0
		Corners         0.0 - 0.0
		Yellow card     0.0  - 0.0
		Red card        0.0   - 0.0
	 season: 2019-2020
		                Home  - Away
		Matches played  19    - 19
		Won             7     - 2
		Lost            9     - 12
		Draws           3     - 5
	Goals scored      22.0  - 19.0
		Goals conceded  30.0  - 19.0
		Shots           249.0 - 210.0
		Shots on target 80.0 - 70.0
		Fouls           231.0 - 220.0
		Corners         111.0 - 89.0
		Yellow card     34.0  - 34.0
		Red card        0.0   - 1.0
	 season: 2020-2021
		                Home  - Away
		Matches played  19    - 19
		Won             7     - 9
		Lost            8     - 7
		Draws           4     - 3
	Goals scored      29.0  - 26.0
		Goals conceded  27.0  - 26.0
		Shots           269.0 - 242.0
		Shots on target 95.0 - 92.0
		Fouls           232.0 - 207.0
		Corners         120.0 - 95.0
		Yellow card     29.0  - 34.0
		Red card        3.0   - 0.0
	 season: 2021-2022
		                Home  - Away
		Matches played  19    - 19
		Won             6     - 7
		Lost            8     - 11
		Draws           5     - 1
	Goals scored      29.0  - 23.0
		Goals conceded  29.0  - 23.0
		Shots           235.0 - 219.0
		Shots on target 86.0 - 76.0
		Fouls           190.0 - 211.0
		Corners         90.0 - 106.0
		Yellow card     31.0  - 46.0
		Red card        2.0   - 0.0

compare teams

home vs away (which was best for a team)